export { computeProductMetrics, computeStoreMetrics } from "./metrics-engine";
export type { ProductMetrics, StoreMetrics } from "./metrics-engine";
export { diagnoseProducts, computeHealthScore } from "./diagnosis-engine";
export type { Diagnosis, HealthScore } from "./diagnosis-engine";
export { generateActions, computePriority } from "./decision-engine";
export type { Action } from "./decision-engine";
export { analyzeCampaigns } from "./marketing-engine";
export type { CampaignMetrics, CampaignAlert, MarketingAnalysis } from "./marketing-engine";
export { computeProductPnL } from "./profit-engine";
export type { ProductPnL, ProfitAnalysis } from "./profit-engine";
