/**
 * ProcureWise 电商领域知识库 v2.0
 *
 * 80条结构化知识条目，覆盖5大类。
 * 每条知识包含完整的新鲜度元数据，支持自动过期检测。
 *
 * 挥发度分类：
 *   - evergreen: 永不过时（方法论/策略）
 *   - annual: 年度更新（行业基准/年度报告）
 *   - quarterly: 季度更新（平台费率/政策）
 *   - event_driven: 事件驱动（大促日历/临时政策）
 *
 * 置信度分级：
 *   - Tier 1 (≥0.90): 官方数据，可直接引用
 *   - Tier 2 (0.70-0.89): 行业共识，可参考但需注明
 *   - Tier 3 (0.50-0.69): LLM推断，需验证
 *   - <0.50: 不注入
 */

export interface KnowledgeEntry {
  id: string;
  category: 'platform_rule' | 'industry_benchmark' | 'methodology' | 'alert_rule' | 'supply_chain';
  title: string;
  content: string;

  // 新鲜度元数据
  validFrom: string;       // ISO日期，知识生效日期
  validUntil: string;      // ISO日期，预计过期日
  lastVerified: string;    // ISO日期，最后验证日期
  volatility: 'evergreen' | 'annual' | 'quarterly' | 'event_driven';

  // 来源追溯
  source: string;
  sourceUrl?: string;
  confidence: number;      // 0-1

  // 检索字段
  keywords: string[];
  synonyms?: string[];
  tags: string[];

  // 上下文触发
  contextTriggers?: {
    metric?: string;
    threshold?: string;
    platform?: string;
  }[];

  // AI使用提示
  aiUsageHint?: string;

  // 统计（运行时更新）
  injectionCount?: number;
  userApprovalRate?: number;
}

export const KNOWLEDGE: KnowledgeEntry[] = [

  // ═══════════════════════════════════════════════
  // 大类一：平台规则 (platform_rule) — 22条
  // ═══════════════════════════════════════════════

  {
    id: "platform_tmall_fee_2026",
    category: "platform_rule",
    title: "天猫2026年费率结构",
    content: "天猫佣金率按类目0.5%-10%，服装类5%-8%，数码类可达10%以上。2026年新商免年费（原3万/6万两档），单季贡献行业50%+GMV的新商家单店最高激励300万。运费险由商家承担，费率0.5%-2%按历史退货率浮动。另有30天免息贷款、生意参谋免费、运费险减免等20项普惠权益。'服务即增长'—服务分低的店铺获取流量困难。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "天猫商家中心2026年费率公告", sourceUrl: "https://maowo.tmall.com/",
    confidence: 0.95,
    keywords: ["天猫", "tmall", "费率", "佣金", "年费", "保证金", "技术服务费"],
    synonyms: ["天猫佣金", "天猫扣点", "天猫费用", "天猫成本"],
    tags: ["天猫", "费率", "佣金", "成本计算", "2026"],
    contextTriggers: [{ platform: "tmall" }],
    aiUsageHint: "计算天猫平台利润时使用。注意区分新商（免年费）和老商（可能仍在缴纳年费）。",
  },
  {
    id: "platform_taobao_fee_2026",
    category: "platform_rule",
    title: "淘宝2026年费率结构",
    content: "淘宝C店佣金率按类目2%-5%，无年费。保证金根据类目不同1,000-10,000元不等。运费险约0.5%-1%。相比天猫，淘宝运营成本更低，但流量获取难度更大。2026年淘宝强化内容化和直播，部分类目有流量扶持政策。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "淘宝商家中心2026年规则", sourceUrl: "https://sell.taobao.com/",
    confidence: 0.90,
    keywords: ["淘宝", "taobao", "C店", "佣金", "保证金"],
    synonyms: ["淘宝扣点", "淘宝费用", "淘宝成本"],
    tags: ["淘宝", "费率", "佣金", "2026"],
    contextTriggers: [{ platform: "taobao" }],
    aiUsageHint: "淘宝C店运营成本低于天猫，但计算利润时仍需扣除佣金和运费险。",
  },
  {
    id: "platform_jd_fee_2026",
    category: "platform_rule",
    title: "京东2026年费率结构",
    content: "京东POP商家佣金率按类目2%-10%，主流类目集中在5%-8%。平台使用费统一1,000元/月（少数类目500元/月或免费）。保证金通常3万-5万元（部分特殊类目如平板电脑6万，手表/无人机/汽车等可达10万）。结算周期：POP商家T+1/T+2天；自营商家30-60天协商确定。2026年响应六部门新政：降佣+返佣并举，部分类目返佣至广告账户。京东自营与POP店数据口径不同，分析时需区分。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "京东商家中心2026年规则", sourceUrl: "https://help.jd.com/",
    confidence: 0.93,
    keywords: ["京东", "jd", "POP", "自营", "佣金", "平台使用费", "保证金", "结算"],
    synonyms: ["京东扣点", "京东费用", "京东成本", "京东平台费"],
    tags: ["京东", "费率", "佣金", "结算", "2026"],
    contextTriggers: [{ platform: "jd" }],
    aiUsageHint: "京东自营和POP的数据口径不同。POP结算快但需另付平台使用费；自营结算周期长但平台承担更多运营责任。",
  },
  {
    id: "platform_pdd_fee_2026",
    category: "platform_rule",
    title: "拼多多2026年费率结构",
    content: "拼多多佣金约2%技术服务费（黑标品牌商品）。保证金：个人店铺2,000元，企业店铺1,000元（虚拟类目10,000元）。2026年3月百亿补贴新规：价格要求从'全网最低'放宽为'具备较强价格竞争力'，临期商品标准更严格。2026年4月优惠联合营销：平台全额承担优惠成本但商家需配合开票。⚠️ 财税合规新要求：商家需向平台开具'合作服务费'发票，未开票将冻结30%资金。'仅退款'政策：已发货订单仅退款转为拒收退款，商家可自主设置退款策略。价格违规处罚：分级扣分制（12分限流/24分清退）。",
    validFrom: "2026-03-01", validUntil: "2026-09-01", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "拼多多商家后台2026年规则中心", sourceUrl: "https://mms.pinduoduo.com/",
    confidence: 0.92,
    keywords: ["拼多多", "pdd", "佣金", "技术服务费", "保证金", "百亿补贴", "财税"],
    synonyms: ["拼多多扣点", "拼多多费用", "拼多多成本", "拼夕夕"],
    tags: ["拼多多", "费率", "佣金", "财税合规", "2026"],
    contextTriggers: [{ platform: "pdd" }],
    aiUsageHint: "拼多多财税合规新规是2026年关键风险点——未开票的商家面临30%资金冻结。计算利润时需将这部分作为隐性资金成本考虑。",
  },
  {
    id: "platform_douyin_fee_2026",
    category: "platform_rule",
    title: "抖音电商2026年费率结构",
    content: "抖音电商2026年重大变化：1)全类目免佣升级：使用'千川·乘方'推广，技术服务费降至0.6%（全类目全场景开放），不使用千川的佣金率为2%-5%。2)达人服务费分级制（6月生效）：按合规/内容/结算健康度评级—A级10%+返现、C级20%、D级40%，超六成达人获A/B+级。3)达人佣金率下限从1%上调至5%（4月生效）。4)联盟双佣金模式：投流/非投流订单拆分分别计佣。5)日用品类佣金下调至2%。6)保证金大幅下调：34个一级类目最高降幅85%，部分类目降至500元，近70%商家保证金降幅超50%。7)0元入驻：新商家无需立即缴保证金。8)AI工具免费开放。结算周期与店铺体验分挂钩：≥4.4分→确认收货后4天；<4.4分→10天；新手期→14-30天。",
    validFrom: "2026-06-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "抖音电商2026年6月达人服务费分级制公告", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.93,
    keywords: ["抖音", "douyin", "抖店", "佣金", "达人", "千川", "保证金", "体验分"],
    synonyms: ["抖音扣点", "抖音费用", "抖音成本", "抖音达人费", "抖音佣金"],
    tags: ["抖音", "费率", "达人", "佣金", "千川", "2026"],
    contextTriggers: [{ platform: "douyin" }],
    aiUsageHint: "⚠️ 抖音2026年最关键的利润变量是达人分级。A级达人佣金10%+返现 vs D级40%，同一商品利润差4倍。必须询问用户使用的达人等级或根据数据推断。",
  },
  {
    id: "platform_douyin_influencer_grade",
    category: "platform_rule",
    title: "抖音达人佣金分级制度详解",
    content: "2026年6月生效的抖音达人服务费分级制：按合规健康度、内容健康度、结算健康度三项指标评级。A级：10%佣金+返现奖励；B+级：约15%佣金；C级：20%佣金；D级：40%佣金（惩罚性费率）。超六成达人获A/B+级。达人佣金率下限从1%上调至5%。联盟双佣金模式下，投流订单和非投流订单分别计佣。商家应优先选择A/B+级达人合作，D级达人ROI几乎不可能为正。",
    validFrom: "2026-06-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "抖音电商达人服务费分级制公告（2026年6月）", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.90,
    keywords: ["达人分级", "达人佣金", "达人等级", "A级达人", "D级达人", "抖音达人"],
    synonyms: ["达人费率", "达人扣点", "抖音达人费", "达人分成"],
    tags: ["抖音", "达人", "佣金分级", "ROI", "2026"],
    contextTriggers: [{ platform: "douyin" }, { metric: "influencer_commission" }],
    aiUsageHint: "当用户数据中包含达人相关字段时，必须提醒用户注意达人分级对利润的影响。A级vs D级利润差可达4倍。",
  },
  {
    id: "platform_tmall_incentive_2026",
    category: "platform_rule",
    title: "天猫2026年新商激励政策",
    content: "2026年天猫新商政策力度空前：1)新入驻商家免年费（年省3-6万元）；2)单季贡献行业50%+GMV的新商家，单店最高激励300万；3)30天免息贷款；4)生意参谋工具免费开放；5)运费险减免；6)共20项普惠权益。但'服务即增长'——服务质量差（DSR低）的店铺会越来越难获取流量。新商红利窗口可能随时调整。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "天猫商家中心2026年新商激励公告", sourceUrl: "https://maowo.tmall.com/",
    confidence: 0.90,
    keywords: ["天猫新商", "免年费", "激励", "新店", "入驻"],
    synonyms: ["天猫开店", "天猫入驻", "天猫政策"],
    tags: ["天猫", "新商", "激励", "2026"],
    contextTriggers: [{ platform: "tmall" }],
    aiUsageHint: "当用户是天猫新商家时，提醒其享受免年费政策（原3-6万/年），但需关注DSR评分以维持流量。",
  },
  {
    id: "platform_douyin_qianchuan",
    category: "platform_rule",
    title: "抖音千川·乘方投流优惠机制",
    content: "抖音2026年推出'千川·乘方'推广工具，核心机制是'工具换优惠'：使用千川·乘方进行推广投放的商家，技术服务费降至0.6%（全类目全场景开放）。不使用千川的商家佣金率为2%-5%。这意味着：投流→低佣0.6%，不投流→正常佣金2%-5%。商家需要计算：投流成本 + 0.6%佣金 vs 不投流 + 2-5%佣金，哪个总成本更低。千川·乘方还提供AI投放优化功能。",
    validFrom: "2026-03-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "抖音电商千川·乘方产品公告", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.88,
    keywords: ["千川", "乘方", "投流", "推广", "0.6%", "低佣"],
    synonyms: ["抖音投流", "抖音推广", "千川推广"],
    tags: ["抖音", "千川", "投流", "佣金", "2026"],
    contextTriggers: [{ platform: "douyin" }, { metric: "ad_cost" }],
    aiUsageHint: "分析抖音利润时，必须区分是否使用千川·乘方。如果用了→佣金0.6%，但需额外计算投流成本。如果没用→佣金2-5%。两者的利润模型完全不同。",
  },
  {
    id: "platform_settlement_comparison",
    category: "platform_rule",
    title: "四大平台结算周期对比",
    content: "各平台结算周期直接影响商家的现金流管理。天猫/淘宝：确认收货后结算（通常7-15天）。京东：POP商家T+1~T+2天（行业最快）；自营商家30-60天协商确定。拼多多：确认收货后结算（通常7-15天），但财税合规要求商家开票，否则冻结30%资金。抖音：体验分≥4.4→确认收货后4天；<4.4→10天；新手期→14-30天。结算周期最短的是京东POP（T+1），最长的是京东自营（最长60天）和抖音新手期（最长30天）。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "各平台商家中心2026年规则综合", sourceUrl: "",
    confidence: 0.90,
    keywords: ["结算", "回款", "账期", "现金流", "T+1"],
    synonyms: ["结算周期", "回款周期", "账期对比", "资金回笼"],
    tags: ["结算", "现金流", "对比", "2026"],
    aiUsageHint: "分析多平台现金流时，需考虑不同结算周期对资金压力的影响。京东POP最快(T+1)，京东自营最慢(最长60天)。",
  },
  {
    id: "platform_pdd_tax_compliance",
    category: "platform_rule",
    title: "拼多多2026年财税合规新规",
    content: "拼多多2026年最重要的合规变化：商家需向平台开具'合作服务费'发票。未按规定开票的商家，平台将冻结其30%的账户资金直至完成开票。这意味着：如果一个商家拼多多账户有10万余额但未开票，其中3万将被冻结。这30%应被视为隐性资金成本——虽然最终可以解冻，但占用资金的时间成本约0.5%-1%/月。建议商家：1)及时配合开票 2)预留30%作为不可动用资金 3)将资金冻结成本纳入利润模型。",
    validFrom: "2026-04-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "quarterly",
    source: "拼多多商家后台2026年财税合规公告", sourceUrl: "https://mms.pinduoduo.com/",
    confidence: 0.92,
    keywords: ["拼多多", "财税", "开票", "发票", "冻结", "合规"],
    synonyms: ["拼多多税务", "拼多多发票", "资金冻结"],
    tags: ["拼多多", "财税合规", "资金冻结", "2026"],
    contextTriggers: [{ platform: "pdd" }],
    aiUsageHint: "⚠️ 拼多多商家利润计算中必须考虑30%资金冻结的隐性成本。按资金成本0.5%/月计算，冻结3万=月隐性成本¥150。",
  },
  {
    id: "platform_refund_policy_2026",
    category: "platform_rule",
    title: "2026年各平台退款政策变化",
    content: "2026年退款政策重大变化：拼多多已发货订单仅退款转为拒收退款，商家可自主设置退款策略。淘宝/天猫：维持7天无理由退货，部分类目15天。京东：自营7天无理由，POP店参照执行。抖音：与体验分挂钩，高体验分店铺可享更灵活的退款策略。整体趋势：平台从'无脑偏向消费者'转向'平衡买卖双方权益'。退货率仍然是核心KPI——每降低1个百分点，直接增加对应比例的利润。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "各平台2026年退款政策综合",
    confidence: 0.85,
    keywords: ["退款", "退货", "仅退款", "无理由", "售后"],
    synonyms: ["退款政策", "退货规则", "售后规则"],
    tags: ["退款", "退货", "政策", "2026"],
    aiUsageHint: "分析退货率异常时，需结合平台的退款政策变化给出解释。",
  },
  {
    id: "platform_jd_self_operated_vs_pop",
    category: "platform_rule",
    title: "京东自营 vs POP 商家运营差异",
    content: "京东自营和POP是两种截然不同的经营模式：1)自营——京东作为采购方，商家是供应商，结算周期30-60天，平台承担主要运营责任，适合品牌方/大厂。2)POP——商家自主运营，类似天猫旗舰店，结算T+1~T+2天，需自行承担客服/物流/售后。关键差异：流量分配（自营获平台优先流量）、利润率（自营价低量稳，POP价高但需承担平台费）、账期（POP更快回款）、结算（POP日结 vs 自营月结/协商）。分析京东数据时，必须区分自营和POP——两者利润结构、周转效率完全不同。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "京东商家中心运营模式说明", sourceUrl: "https://help.jd.com/",
    confidence: 0.93,
    keywords: ["京东自营", "POP", "京东运营模式", "自营vsPOP"],
    synonyms: ["京东自营店", "京东POP店", "京东模式"],
    tags: ["京东", "自营", "POP", "运营模式"],
    contextTriggers: [{ platform: "jd" }],
    aiUsageHint: "分析京东利润时必须先确认数据类型是自营还是POP，两者利润模型差异巨大。",
  },
  {
    id: "platform_jd_refund_policy_2026",
    category: "platform_rule",
    title: "京东2026年退款/售后政策",
    content: "京东2026年售后政策要点：1)自营7天无理由退货，POP店参照执行但可自定义部分规则。2)闪电退款：信用良好用户可享受先退款后退货。3)价格保护：部分类目支持价保7-30天。4)售后响应时效：自营24小时内处理，POP商家48小时内。5)纠纷处理：平台介入后通常偏向维护消费者权益，商家举证责任较重。退货率高的京东POP商家会被限制活动报名资格。京东的售后体验直接影响店铺评分和搜索权重。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "京东商家中心2026年售后规则", sourceUrl: "https://help.jd.com/",
    confidence: 0.88,
    keywords: ["京东退款", "京东售后", "退货", "价保", "闪电退款"],
    synonyms: ["京东退货", "京东售后规则"],
    tags: ["京东", "退款", "售后", "2026"],
    contextTriggers: [{ platform: "jd" }],
    aiUsageHint: "京东退货率分析时注意区分自营和POP——POP商家对售后响应更敏感。",
  },
  {
    id: "platform_taobao_live_2026",
    category: "platform_rule",
    title: "淘宝2026年直播电商规则",
    content: "淘宝2026年强化内容化和直播电商：1)直播流量扶持：优质直播间可获得首页流量加权。2)达人合作模式：走淘宝联盟分佣，佣金率10%-30%视类目。3)直播间专属优惠券：商家可设置限时折扣，影响利润模型。4)保证金要求：开通直播需缴纳保证金（通常5000-20000元）。5)违规处罚：虚假宣传/价格欺诈/刷单均可能被封直播间。淘宝直播的核心指标：GPM（千次观看成交额）、人均停留时长、转化率。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "淘宝直播商家规则2026", sourceUrl: "https://live.taobao.com/",
    confidence: 0.85,
    keywords: ["淘宝直播", "淘宝内容", "淘宝达人", "直播间", "淘宝联盟"],
    synonyms: ["淘宝内容电商", "淘宝主播", "直播带货"],
    tags: ["淘宝", "直播", "内容电商", "2026"],
    contextTriggers: [{ platform: "taobao" }],
    aiUsageHint: "分析淘宝直播数据时，GPM比GMV更能反映真实经营效率。佣金率通常10%-30%。",
  },
  {
    id: "platform_taobao_ad_fee_2026",
    category: "platform_rule",
    title: "淘宝2026年推广费用结构",
    content: "淘宝主要推广工具及费用结构（2026年）：1)直通车：按点击付费(CPC)，类目竞争度决定出价，服装类CPC约0.5-3元，3C类约1-5元。行业健康ROI>3。2)引力魔方：按展现付费(CPM)，适合拉新和人群圈选，千次展现成本约5-20元。3)万相台无界版：AI智能投放，按目标付费（成交/收藏/加购），ROI目标建议设为保本点的1.5倍。4)淘宝联盟：按成交付费(CPS)，佣金率10%-30%。推广费用通常占销售额15%-25%，过高则压缩利润。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "淘宝商家中心推广工具2026", sourceUrl: "https://www.taobao.com/",
    confidence: 0.85,
    keywords: ["淘宝直通车", "引力魔方", "万相台", "淘宝联盟", "CPC", "CPM"],
    synonyms: ["淘宝推广", "淘宝广告", "直通车费用"],
    tags: ["淘宝", "推广", "广告", "ROI", "2026"],
    contextTriggers: [{ platform: "taobao" }, { metric: "ad_cost" }],
    aiUsageHint: "淘宝推广费用占销售额15%-25%为正常范围。直通车ROI<3说明需要优化主图/详情页/关键词。",
  },
  {
    id: "platform_pdd_ad_fee_2026",
    category: "platform_rule",
    title: "拼多多2026年推广费用结构",
    content: "拼多多主要推广工具（2026年）：1)全站推广：按曝光付费(CPM)或按成交付费(OCPX)，类目CPM约3-15元。2)搜索推广：按点击付费(CPC)，关键词竞价模式，CPC约0.2-2元。3)场景推广：商品详情页/类目页展示，CPM约2-10元。4)明星店铺：品牌曝光工具，按天收费（数百至数千元/天）。拼多多推广ROI健康值2-4。⚠️ 注意：拼多多用户价格敏感度高，推广ROI计算方法与其他平台不同——拼多多用销售额/推广费而非利润/推广费。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "拼多多商家后台推广工具2026", sourceUrl: "https://mms.pinduoduo.com/",
    confidence: 0.82,
    keywords: ["拼多多推广", "全站推广", "搜索推广", "OCPX", "CPM", "CPC"],
    synonyms: ["拼多多广告", "拼多多推广费"],
    tags: ["拼多多", "推广", "广告", "ROI", "2026"],
    contextTriggers: [{ platform: "pdd" }, { metric: "ad_cost" }],
    aiUsageHint: "拼多多推广费用需严格控制——用户价格敏感度高，推广ROI>3是健康线。",
  },
  {
    id: "platform_douyin_ad_fee_2026",
    category: "platform_rule",
    title: "抖音电商2026年推广费用结构",
    content: "抖音电商推广工具（2026年）：1)千川·乘方：技术服务费降至0.6%（使用千川推广时），同时承担投流费用。投流ROI目标1.5-4。2)DOU+：短视频加热工具，按展现付费，100元起投。3)品牌广告：开屏/信息流广告，CPM约20-50元。4)达人合作：佣金率A级10%+返现，C级20%，D级40%。5)联盟：按成交付费，佣金率5%-30%。⚠️ 抖音推广最特殊的点是'双佣金'——投流订单投流费+佣金同时计算。分析利润时必须同时考虑投流费和达人佣金。",
    validFrom: "2026-06-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "抖音电商巨量千川2026产品公告", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.90,
    keywords: ["千川", "乘方", "DOU+", "抖音推广", "投流", "CPM", "达人佣金"],
    synonyms: ["抖音广告", "抖音投流", "千川费用"],
    tags: ["抖音", "推广", "千川", "达人", "ROI", "2026"],
    contextTriggers: [{ platform: "douyin" }, { metric: "ad_cost" }],
    aiUsageHint: "⚠️ 抖音利润分析最复杂——必须同时计算投流费+佣金+平台费三重成本。使用千川时佣金0.6%，但投流费另算。",
  },
  {
    id: "platform_douyin_experience_score",
    category: "platform_rule",
    title: "抖音店铺体验分体系",
    content: "抖音店铺体验分（2026年）直接影响流量分配和结算周期：1)计算维度：商品体验（差评率/品质退货率，权重50%）、物流体验（发货时效/揽收时效，权重15%）、服务体验（投诉率/纠纷处理率/IM回复时长，权重35%）。2)分数区间：≥4.4分为优秀，4.0-4.4分为良好，<4.0分为待改进。3)流量影响：体验分直接影响推荐流量权重，分数越低流量越少。4)结算影响：≥4.4→确认收货后4天结算；<4.4→10天；新手期→14-30天。5)保证金：体验分过低可能触发保证金上涨。提升路径：降低差评率（控制产品质量）、加速发货（优化物流）、提升IM响应速度（<30秒）。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "抖音电商店铺体验分规则2026", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.90,
    keywords: ["体验分", "抖音评分", "商品体验", "物流体验", "服务体验", "4.4分"],
    synonyms: ["抖音店铺分", "抖店评分", "体验分数"],
    tags: ["抖音", "体验分", "评分", "流量", "2026"],
    contextTriggers: [{ platform: "douyin" }, { metric: "stockHealth" }],
    aiUsageHint: "抖音商家体验分<4.4时，结算周期从4天延长到10天，直接影响现金流。分析时应提醒用户。",
  },
  {
    id: "platform_promotion_calendar_2026",
    category: "platform_rule",
    title: "2026年电商大促日历与平台活动",
    content: "2026年重点营销节点及利润影响：1)618年中大促（6月1日-18日）：全年第二大促销，利润率通常压缩30%-50%。平台佣金不变，但满减/优惠券由商家承担。2)双11（11月11日）：全年最大促销，利润率压缩50%-70%。需提前备货并计算大促后的退货潮。3)双12（12月12日）：双11余温，利润率压缩20%-40%。4)年货节（1月）：春节前消费高峰，物流成本上升。5)38女神节（3月8日）：美妆/服饰类目重点节点。6)99大促（9月9日）：拼多多/抖音主战场。7)新势力周/新风尚：淘宝/天猫服饰类目月度活动。策略：大促前备货量按平日销量的3-5倍准备，大促后立即启动退货处理和库存清理。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "event_driven",
    source: "各平台2026年营销活动日历综合", sourceUrl: "",
    confidence: 0.85,
    keywords: ["大促", "618", "双11", "双12", "年货节", "促销", "活动日历"],
    synonyms: ["促销节点", "营销节点", "电商节日", "大促日历"],
    tags: ["大促", "促销", "营销", "活动", "2026"],
    contextTriggers: [{ metric: "seasonality" }],
    aiUsageHint: "大促期间利润分析需考虑：1)利润率临时下降是正常的 2)大促后退货率通常上升20%-40% 3)建议用'大促前后对比'而非单日数据评估。",
  },
  {
    id: "platform_tmall_ad_fee_2026",
    category: "platform_rule",
    title: "天猫2026年推广费用结构",
    content: "天猫主要推广工具及费用结构（2026年）：1)直通车：按点击付费(CPC)，服装类CPC约0.5-3元，3C类约1-5元。健康ROI>3。2)引力魔方：按展现付费(CPM)，适合人群圈选和拉新，千次展现约5-20元。3)万相台无界版：AI智能投放，按成交/收藏/加购付费，支持自动出价。4)淘宝联盟：按成交付费(CPS)，佣金率10%-30%。天猫推广费用通常占销售额15%-25%。2026年天猫流量成本持续上涨，建议ROI目标不低于2.5，低于此值需暂停并优化。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "天猫商家中心推广工具2026", sourceUrl: "https://maowo.tmall.com/",
    confidence: 0.85,
    keywords: ["天猫直通车", "天猫推广", "万相台", "引力魔方", "天猫广告"],
    synonyms: ["天猫推广费", "天猫广告费", "天猫投放"],
    tags: ["天猫", "推广", "广告", "ROI", "2026"],
    contextTriggers: [{ platform: "tmall" }, { metric: "ad_cost" }],
    aiUsageHint: "天猫推广费用分析时，注意区分拉新成本和复购成本——拉新ROI通常低于复购。",
  },
  {
    id: "platform_taobao_refund_policy_2026",
    category: "platform_rule",
    title: "淘宝2026年退款/售后规则",
    content: "淘宝2026年售后规则要点：1)7天无理由退货（部分类目15天）。2)极速退款：信用良好的淘宝会员可享受先退款后退货。3)运费规则：包邮商品退货运费由商家承担（质量问题除外）；不包邮商品，用户仅需承担去程运费。4)售后响应时效：商家需在48小时内处理退款申请，超时系统自动同意。5)恶意退款防控：淘宝推出'极速退款信用体系'，信用差的用户无法享受极速退款。6)评价管理：中差评可在交易完成后15天内协商修改。售后体验直接影响店铺DSR评分。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "淘宝规则中心2026", sourceUrl: "https://rule.taobao.com/",
    confidence: 0.85,
    keywords: ["淘宝退款", "淘宝售后", "7天无理由", "极速退款", "DSR"],
    synonyms: ["淘宝退货", "淘宝售后规则", "淘宝评价"],
    tags: ["淘宝", "退款", "售后", "评价", "2026"],
    contextTriggers: [{ platform: "taobao" }],
    aiUsageHint: "淘宝DSR评分直接影响店铺流量权重，分析退货率异常时需关联DSR变化。",
  },
  {
    id: "platform_tmall_refund_policy_2026",
    category: "platform_rule",
    title: "天猫2026年退款/售后规则",
    content: "天猫2026年售后规则要点：1)7天无理由退货，部分类目（定制/生鲜/虚拟）不支持。2)运费规则：包邮商品退货运费由商家承担；不包邮商品，用户承担去程运费，商家承担返程运费。3)极速退款：天猫88VIP会员可享受先退款后退货。4)售后响应：商家需在72小时内处理，超时自动执行退款。5)品质退款：因质量问题产生的退款，会影响店铺服务评分和搜索排名。6)仅退款限制：2026年天猫收紧'仅退款'门槛，需要商家举证后才能拒绝。7)申诉机制：商家可通过天猫客服介入申诉恶意退款。天猫退款率直接影响店铺权重和活动报名资格。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫规则中心2026", sourceUrl: "https://rule.tmall.com/",
    confidence: 0.88,
    keywords: ["天猫退款", "天猫售后", "品质退款", "88VIP", "天猫评价"],
    synonyms: ["天猫退货", "天猫售后规则", "天猫申诉"],
    tags: ["天猫", "退款", "售后", "服务分", "2026"],
    contextTriggers: [{ platform: "tmall" }],
    aiUsageHint: "天猫品质退款率是核心健康指标——不仅影响利润，还直接影响搜索排名和活动资格。",
  },
  {
    id: "platform_pdd_refund_policy_2026",
    category: "platform_rule",
    title: "拼多多2026年退款/售后规则",
    content: "拼多多2026年售后规则要点：1)已发货订单仅退款政策收紧：从'无理由仅退款'转为'拒收退款'，商家可自主设置退款策略（全额仅退款/拒收回部分退款/拦截退回）。2)退货退款：用户需先退货再退款，物流由用户选择。3)运费规则：质量问题商家承担，非质量问题用户承担。4)售后时效：商家需在48小时内处理，超时自动同意。5)恶意退款防控：用户仅退款次数过多会被标记，影响后续退款成功率。6)平台介入：拼多多偏向消费者，但商家可通过举证申诉。⚠️ 拼多多退款率直接影响店铺星级和流量分配，且拼多多用户对价格极度敏感。",
    validFrom: "2026-04-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "拼多多商家后台2026年售后规则", sourceUrl: "https://mms.pinduoduo.com/",
    confidence: 0.88,
    keywords: ["拼多多退款", "拼多多售后", "仅退款", "拒收退款", "恶意退款"],
    synonyms: ["拼多多退货", "拼多多售后", "拼多多仅退款"],
    tags: ["拼多多", "退款", "售后", "2026"],
    contextTriggers: [{ platform: "pdd" }],
    aiUsageHint: "拼多多退款政策是2026年最大变量——'仅退款'收紧后，商家需要重新评估利润模型中的退货成本。",
  },
  {
    id: "platform_douyin_refund_policy_2026",
    category: "platform_rule",
    title: "抖音电商2026年退款/售后规则",
    content: "抖音电商2026年售后规则要点：1)7天无理由退货，生鲜/定制类目除外。2)极速退款：高体验分店铺用户可享受先退款后退货。3)运费规则：包邮商品商家承担退货运费（质量问题由商家承担全部运费）。4)售后响应：商家需在48小时内处理，影响体验分。5)退货率影响：体验分中的商品体验维度直接包含退货率指标，退货率高→体验分低→流量减少。6)达人责任：达人直播带出的商品，部分售后由商家和达人共同承担。7)仅退款：抖音未如拼多多般放开，但仍需商家及时处理。抖音售后体验是流量分配的核心指标。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "抖音电商商家后台2026年售后规则", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.85,
    keywords: ["抖音退款", "抖音售后", "体验分", "退货率", "达人售后"],
    synonyms: ["抖店退款", "抖音退货", "抖音售后规则"],
    tags: ["抖音", "退款", "售后", "体验分", "2026"],
    contextTriggers: [{ platform: "douyin" }],
    aiUsageHint: "抖音售后与体验分强绑定——退货率直接影响推荐流量。分析退货率时应同时提醒体验分风险。",
  },
  {
    id: "platform_jd_ad_fee_2026",
    category: "platform_rule",
    title: "京东2026年推广费用结构",
    content: "京东主要推广工具及费用结构（2026年）：1)京东快车：按点击付费(CPC)，搜索广告，CPC约1-5元，行业健康ROI>3。2)京东直投：DSP展示广告，CPM约10-30元。3)购物触点：商品详情页推荐位，CPC约0.5-3元。4)京挑客：按成交付费(CPS)，佣金率5%-30%。5)品牌速递：品牌曝光工具，按天收费。京东推广费用通常占销售额10%-20%。京东用户决策路径长，转化周期通常比淘宝/抖音长3-5天，ROI计算周期也应相应延长。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "京东商家中心推广工具2026", sourceUrl: "https://help.jd.com/",
    confidence: 0.85,
    keywords: ["京东快车", "京东直投", "购物触点", "京挑客", "京东推广", "CPC"],
    synonyms: ["京东广告", "京东推广费", "京东投放"],
    tags: ["京东", "推广", "广告", "ROI", "2026"],
    contextTriggers: [{ platform: "jd" }, { metric: "ad_cost" }],
    aiUsageHint: "京东推广ROI计算周期应比淘宝/抖音长3-5天，因为京东用户决策更理性。",
  },
  {
    id: "platform_jd_new_merchant_2026",
    category: "platform_rule",
    title: "京东2026年新商家入驻政策",
    content: "京东2026年新商家入驻政策：1)保证金下调：部分类目从5万降至3万，家居/服饰类目最低1万。2)平台使用费：新商家首年免平台使用费（原1000元/月）。3)返佣政策：部分类目推广费返佣20%-30%，直接返到广告账户。4)绿色通道：品牌商家/工厂店可享快速审核（3-7天）。5)新商流量扶持：入驻前30天可获得首页推荐位测试资格。6)培训体系：京东商家大学提供免费课程，覆盖运营/推广/客服。7)物流支持：部分城市可享受京东物流优先入仓。POP vs 自营选择建议：有品牌力和供应链能力的优先自营，起步阶段建议POP（门槛低、回款快）。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "京东招商2026年新政策", sourceUrl: "https://help.jd.com/",
    confidence: 0.88,
    keywords: ["京东新商", "京东入驻", "京东保证金", "平台使用费", "返佣"],
    synonyms: ["京东开店", "京东招商", "京东新商家"],
    tags: ["京东", "新商", "入驻", "2026"],
    contextTriggers: [{ platform: "jd" }],
    aiUsageHint: "京东新商家首年免平台使用费，保证金部分类目下调。起步阶段建议先做POP降低风险。",
  },
  {
    id: "platform_taobao_shop_types",
    category: "platform_rule",
    title: "淘宝店铺类型与规则差异",
    content: "淘宝店铺三种类型及差异：1)C店（个人店）：无年费，保证金1000-10000元（视类目），佣金率2%-5%。适合个人卖家/小商家。2)企业店：需营业执照，保证金5000-50000元，佣金率与C店相同。适合小型企业。3)天猫店：需企业资质+品牌授权，保证金5-10万，年费3-6万（2026年新商免年费），佣金率5%-8%。适合品牌方/大商家。关键差异：流量权重（天猫>企业>C）、搜索排名（天猫优先展示）、活动门槛（大促活动通常仅天猫/企业店可报名）、信任背书（天猫有品牌认证）。2026年淘宝强化内容化和直播，C店可通过直播获得流量倾斜——这是C店的重要机会。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "淘宝商家中心店铺类型说明", sourceUrl: "https://sell.taobao.com/",
    confidence: 0.90,
    keywords: ["C店", "企业店", "天猫店", "淘宝店铺类型", "保证金", "年费"],
    synonyms: ["淘宝店铺", "淘宝开店", "个人店", "企业店铺"],
    tags: ["淘宝", "店铺类型", "入驻", "规则"],
    contextTriggers: [{ platform: "taobao" }],
    aiUsageHint: "淘宝店铺类型直接影响流量权重和活动资格。C店虽佣金低但流量获取难度大，需通过直播/内容突围。",
  },
  {
    id: "platform_pdd_merchant_types",
    category: "platform_rule",
    title: "拼多多店铺类型与保证金规则",
    content: "拼多多店铺类型：1)个人店：个人身份证即可入驻，保证金2000元，适合试水/兼职卖家。2)企业店：需营业执照，保证金1000元（虚拟类目10000元），适合正规经营。3)品牌店：需商标授权，保证金5000-20000元，享受品牌流量扶持。4)旗舰店/专营店：品牌官方/授权经营，保证金1-5万。关键规则：1)保证金可退——关店后30天无售后纠纷可全额退还。2)0元入驻试营业——新商家无需立即缴纳保证金，先试卖30天。3)保证金阶梯调整——店铺星级提升可降低保证金，违规则上涨。4)类目差异——食品/美妆等特殊类目保证金更高。拼多多店铺升级路径：个人店→企业店→品牌店→旗舰店，每升级一级获得更多流量和活动资格。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "拼多多商家后台入驻规则2026", sourceUrl: "https://mms.pinduoduo.com/",
    confidence: 0.88,
    keywords: ["拼多多店铺", "个人店", "企业店", "品牌店", "保证金", "0元入驻"],
    synonyms: ["拼多多开店", "拼多多入驻", "拼多多保证金"],
    tags: ["拼多多", "店铺类型", "入驻", "保证金"],
    contextTriggers: [{ platform: "pdd" }],
    aiUsageHint: "拼多多保证金最低2000元且可退，0元入驻降低了试错成本。建议新商家先以个人店试水。",
  },
  {
    id: "platform_douyin_creator_policy",
    category: "platform_rule",
    title: "抖音电商创作者/达人合作规则",
    content: "抖音电商达人合作核心规则（2026年）：1)合作模式：纯佣金（无坑位费，佣金20%-40%）、坑位费+佣金（固定费用+销售分成）、独家合作（深度绑定，佣金15%-25%）。2)选品要求：食品/美妆需相关资质，3C需3C认证，品牌商品需授权。3)内容规范：禁止虚假宣传/夸大功效/价格欺诈，违规可封号。4)数据结算：按实际成交订单结算，7天无理由退货订单不计佣金（部分达人可协商）。5)达人分级：A级佣金10%+返现，C级20%，D级40%（见platform_douyin_influencer_grade）。6)合作流程：选品→寄样→内容审核→发布→数据复盘。合作风险：达人数据造假（刷单/刷赞）→需独立验证达人历史数据；达人违约（未按合同推广）→需签正式合同。",
    validFrom: "2026-06-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "抖音电商达人合作规则2026", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.88,
    keywords: ["达人合作", "创作者", "坑位费", "佣金", "选品", "抖音达人"],
    synonyms: ["达人规则", "主播合作", "抖音带货"],
    tags: ["抖音", "达人", "合作", "佣金", "2026"],
    contextTriggers: [{ platform: "douyin" }],
    aiUsageHint: "抖音达人合作时，优先选A/B+级达人。D级达人佣金40%+，几乎不可能盈利。合作前务必核实达人历史数据。",
  },
  {
    id: "platform_fee_comparison_table",
    category: "platform_rule",
    title: "五大平台费用结构速查对比",
    content: "五大平台综合费用对比（2026年简化版）：1)佣金率：淘宝2%-5% < 京东2%-10% < 天猫5%-8% < 抖音2%-5%（千川0.6%）< 拼多多约2%。2)年费/平台使用费：淘宝0 < 京东1000元/月 < 天猫0（新商免年费）< 拼多多0 < 抖音0。3)保证金：淘宝1000-10000 < 拼多多2000（个人）1000（企业）< 天猫5-10万 < 京东1-10万 < 抖音500-20000。4)结算周期：京东POP T+1（最快）< 淘宝7-15天 < 拼多多7-15天 < 抖音4-10天 < 京东自营30-60天。5)推广ROI基准：京东3-6 > 淘宝2-5 > 拼多多2-4 > 抖音1.5-4。6)退货率均值：3C 2%-5% < 美妆5%-10% < 食品1%-3% < 京东综合< 淘宝/天猫< 拼多多< 抖音。选择平台建议：有品牌力→天猫/京东；价格优势→拼多多；内容能力→抖音；起步试水→淘宝C店。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "各平台2026年费用综合对比", sourceUrl: "",
    confidence: 0.85,
    keywords: ["平台对比", "费用对比", "佣金对比", "保证金对比", "五大平台"],
    synonyms: ["平台比较", "费用比较", "平台选择", "入驻对比"],
    tags: ["平台对比", "费用", "选择", "2026"],
    contextTriggers: [{ metric: "platform_comparison" }],
    aiUsageHint: "多平台分析时，此表可快速对比各平台费用结构差异。特别注意京东POP结算最快(T+1)而自营最慢(30-60天)。",
  },
  {
    id: "platform_pdd_guarantee_policy",
    category: "platform_rule",
    title: "拼多多保证金与店铺星级体系",
    content: "拼多多保证金与店铺星级规则（2026年）：1)保证金阶梯：个人店2000元，企业店1000元，品牌店5000-20000元，旗舰店1-5万。2)保证金调整：店铺星级越高保证金越低，违规则上涨。3)0元入驻：新商家可先0元试营业30天，期间功能受限。4)店铺星级：根据DSR评分（描述/服务/物流）+销量+违规记录综合评定，1-5星。5)星级影响：高星级获得更多流量权重、更低保证金、优先参与活动。6)降级机制：差评率过高/发货超时/虚假宣传均会导致星级下降。保证金与店铺经营强绑定——保证金不仅是入驻门槛，更是平台约束商家行为的杠杆。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "拼多多商家后台2026年店铺规则", sourceUrl: "https://mms.pinduoduo.com/",
    confidence: 0.85,
    keywords: ["拼多多星级", "保证金", "店铺星级", "DSR", "0元入驻"],
    synonyms: ["拼多多店铺星", "拼多多DSR", "拼多多保证金"],
    tags: ["拼多多", "星级", "保证金", "店铺"],
    contextTriggers: [{ platform: "pdd" }],
    aiUsageHint: "拼多多店铺星级直接影响流量权重和保证金金额——星级每提升1级，流量权重约提升20%。",
  },
  {
    id: "platform_douyin_service_commitment",
    category: "platform_rule",
    title: "抖音电商服务承诺与违规处罚",
    content: "抖音电商服务承诺要求（2026年）：1)发货时效：普通订单48小时内发货，预售商品需明确标注发货时间。超时发货每单扣保证金0.5-5元，超3天可能限制活动报名。2)退货处理：退货申请48小时内处理，超时系统自动执行退款。3)客服响应：IM消息5分钟内回复率>80%，低于60%扣体验分。4)差评处理：收到差评后7天内可联系买家协商修改，超时锁定。5)违规处罚体系：轻微违规（描述不符）→商品降权/罚款；一般违规（延迟发货）→限制活动/流量降权；严重违规（假货/欺诈）→封店/扣除全部保证金。6)申诉机制：商家可对处罚提出申诉，提供证据后3-5个工作日内回复。抖音处罚特点是'先处罚后申诉'——商家需自行监控商品状态及时处理。",
    validFrom: "2026-01-01", validUntil: "2026-12-31", lastVerified: "2026-07-17",
    volatility: "quarterly",
    source: "抖音电商商家违规处罚规则2026", sourceUrl: "https://school.jinritemai.com/",
    confidence: 0.85,
    keywords: ["抖音违规", "发货时效", "服务承诺", "体验分", "处罚", "扣保证金"],
    synonyms: ["抖店处罚", "抖音违规规则", "抖音服务标准"],
    tags: ["抖音", "违规", "处罚", "服务标准", "2026"],
    contextTriggers: [{ platform: "douyin" }],
    aiUsageHint: "抖音体验分与违规处罚强绑定——发货超时/差评/客服响应慢都会直接影响体验分和流量。",
  },

  // ═══════════════════════════════════════════════
  // 大类二：行业基准 (industry_benchmark) — 22条
  // ═══════════════════════════════════════════════

  {
    id: "benchmark_return_rate_by_category",
    category: "industry_benchmark",
    title: "各类目行业平均退货率（2026年）",
    content: "各品类行业平均退货率（2026年最新数据）：服装鞋包15%-25%，美妆个护5%-10%，3C数码2%-5%，食品饮料1%-3%，家居日用3%-8%，母婴用品3%-6%，运动户外5%-10%，珠宝饰品8%-15%，家电3%-7%，图书音像1%-2%。退货率>类目均值2倍时应重点检查：1)产品质量问题 2)详情页描述准确性（色差/尺码偏差）3)包装运输破损率。退货率每降低1%，对应利润直接提升1%。",
    validFrom: "2026-06-01", validUntil: "2027-06-01", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "天猫商家中心-各类目退货率数据 + 京东商智-行业退货率基准 + 抖音罗盘-商品体验分退货率", sourceUrl: "https://sell.tmall.com/",
    confidence: 0.80,
    keywords: ["退货率", "退款率", "类目", "品类", "行业基准"],
    synonyms: ["退货比例", "退款比例", "行业退货率", "品类退货率"],
    tags: ["退货率", "行业基准", "质量", "品类"],
    aiUsageHint: "用户退货率超过类目均值2倍时，应优先建议检查产品质量和详情页准确性。",
  },
  {
    id: "benchmark_conversion_rate",
    category: "industry_benchmark",
    title: "各平台支付转化率基准（2026年）",
    content: "各平台支付转化率（访客→支付）行业均值：淘宝/天猫2%-4%，京东3%-5%，拼多多4%-8%（低价走量模式转化更高），抖音（直播）1%-3%，抖音（短视频）0.5%-1.5%。转化率下降常见原因：1)竞品降价 2)出现差评 3)主图/详情页优化不足 4)季节因素 5)平台流量质量变化。转化率每提升1个百分点，在相同流量下销售额直接对应增长。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "各平台商家大学+行业报告综合",
    confidence: 0.80,
    keywords: ["转化率", "支付转化", "访客转化", "CVR"],
    synonyms: ["成交率", "下单率", "转化"],
    tags: ["转化率", "行业基准", "各平台", "2026"],
    aiUsageHint: "对比用户数据与行业均值时说明'这是行业参考值，具体受品类/价格带/季节影响'。",
  },
  {
    id: "benchmark_aov_by_platform",
    category: "industry_benchmark",
    title: "各平台客单价基准（2026年）",
    content: "各平台平均客单价（AOV）参考范围：淘宝¥80-200，天猫¥150-500，京东¥200-600，拼多多¥30-80，抖音¥60-200。客单价分析要点：1)客单价持续下滑可能意味着促销过多或低客单商品占比上升 2)客单价突然上升可能是高价值商品占比提升或提价效应 3)不同品类的客单价基准差异巨大，需具体品类具体分析 4)同一商品在不同平台的客单价不同是正常现象（各平台用户画像不同）。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "各平台行业报告2026年综合",
    confidence: 0.78,
    keywords: ["客单价", "AOV", "ARPU", "人均消费", "单价"],
    synonyms: ["平均订单金额", "笔单价", "件单价"],
    tags: ["客单价", "AOV", "行业基准", "2026"],
    aiUsageHint: "引用客单价基准时注意区分平台和品类。拼多多¥30-80 vs 京东¥200-600，平台定位差异决定了客单价差异。",
  },
  {
    id: "benchmark_repurchase_rate",
    category: "industry_benchmark",
    title: "各品类复购率基准",
    content: "电商各品类复购率行业均值（2026年）：食品饮料25%-40%，美妆个护20%-35%，母婴用品30%-50%，宠物用品35%-55%，服装鞋包10%-20%，3C数码5%-10%，家居日用15%-25%。复购率低于行业均值50%以上时：需检查1)产品质量 2)售后体验 3)会员运营体系。提升复购的三大杠杆：会员体系（+5-10%）、售后关怀（+3-5%）、定期新品推送（+5-8%）。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "2026中国电商用户行为报告",
    confidence: 0.78,
    keywords: ["复购", "复购率", "回头客", "老客", "回购"],
    synonyms: ["重复购买", "回头率", "老客率", "客户粘性"],
    tags: ["复购率", "行业基准", "品类", "2026"],
    aiUsageHint: "复购率需要足够的数据积累（至少3个月）才有统计意义。数据太少时标注'样本不足'。",
  },
  {
    id: "benchmark_profit_margin_by_category",
    category: "industry_benchmark",
    title: "各品类毛利率基准（2026年）",
    content: "电商各品类毛利率行业均值：服装鞋包40%-65%，美妆个护50%-70%，3C数码10%-25%，食品饮料20%-40%，家居日用30%-50%，母婴用品25%-45%，运动户外35%-55%，珠宝饰品45%-70%。注意：毛利率≠净利率。扣除平台佣金、运费、广告、退货损耗后，净利率通常为毛利率的40%-60%。例如毛利率50%→净利率约20%-30%。行业整体净利润率较2023年下滑2.1个百分点。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "2026中国电商行业利润报告",
    confidence: 0.75,
    keywords: ["毛利率", "利润率", "毛利", "净利", "利润基准"],
    synonyms: ["毛利水平", "利润水平", "利润空间"],
    tags: ["毛利率", "行业基准", "品类", "2026"],
    aiUsageHint: "⚠️ 务必区分毛利率和净利率。许多商家混淆两者，导致对自己赚钱能力的误判。",
  },
  {
    id: "benchmark_ad_roi",
    category: "industry_benchmark",
    title: "各平台推广ROI基准（2026年）",
    content: "各平台推广ROI（销售额/广告费）行业参考：淘宝直通车ROI 2-5（健康值>3），京东快车ROI 3-6，拼多多全站推ROI 2-4，抖音千川ROI 1.5-4（直播较高，短视频较低）。ROI<2说明投放效率低，需优化主图/详情页/人群定向或暂停。ROI>5说明投放效率优秀。2026年公域平均获客成本280元/人，较2023年上涨47%。47.68%的商家将'流量成本太高'列为最大痛点。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-06",
    volatility: "annual",
    source: "各平台广告投放数据2026年综合", sourceUrl: "",
    confidence: 0.78,
    keywords: ["ROI", "投产", "推广", "广告", "获客成本", "直通车", "千川"],
    synonyms: ["投产比", "广告回报率", "投放效率", "广告ROI"],
    tags: ["ROI", "广告", "行业基准", "获客成本", "2026"],
    aiUsageHint: "计算ROI时务必使用真实利润而非销售额。销售额ROI>3但利润ROI<1是常见陷阱。",
  },
  {
    id: "benchmark_category_clothing",
    category: "industry_benchmark",
    title: "服装鞋包类目全指标基准（2026年）",
    content: "服装鞋包类目2026年行业基准：退货率15%-25%（尺码问题是主因，占退货的40%+）。支付转化率2%-4%（视觉驱动型商品）。客单价¥80-200（女装）/¥150-400（男装）/¥60-150（鞋类）。复购率10%-20%（季节性品类偏低）。毛利率40%-65%（品牌溢价高的可达70%+），净利率约15%-25%。季节性波动大：春秋季为旺季（3-5月、9-11月），夏冬为淡季。尺码表准确性和面料描述真实性直接影响退货率。建议：主图文短视频展示、尺码助手工具、多角度细节图可降低退货率5-10个百分点。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫服饰行业报告2026 + 淘宝女装行业数据", sourceUrl: "",
    confidence: 0.80,
    keywords: ["服装", "鞋包", "服饰", "退货率", "尺码", "季节性"],
    synonyms: ["服装行业", "服饰类目", "服装鞋包", "衣服"],
    tags: ["服装", "行业基准", "退货率", "季节性"],
    contextTriggers: [{ metric: "return_rate" }],
    aiUsageHint: "服装类退货率15%-25%是正常范围，但超过25%需重点检查尺码表和详情页描述。",
  },
  {
    id: "benchmark_category_beauty",
    category: "industry_benchmark",
    title: "美妆个护类目全指标基准（2026年）",
    content: "美妆个护类目2026年行业基准：退货率5%-10%（低于均值，但过敏投诉成本高）。支付转化率3%-5%（品牌认知度驱动）。客单价¥80-300（护肤）/¥50-150（彩妆）/¥30-100（个护）。复购率20%-35%（高复购品类，护肤>彩妆>个护）。毛利率50%-70%（标品溢价空间大），净利率约20%-35%。季节性：护肤品类Q1/Q4旺季（送礼/年终护理），彩妆Q2/Q3旺季（夏季妆容需求）。成分党趋势：用户越来越关注成分表，INCI名称透明度影响转化率。备案要求：特殊用途化妆品必须有特证，否则无法上架。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫美妆行业报告2026 + 抖音美妆数据", sourceUrl: "",
    confidence: 0.78,
    keywords: ["美妆", "个护", "护肤", "彩妆", "成分", "过敏"],
    synonyms: ["化妆品", "护肤品", "美妆行业"],
    tags: ["美妆", "行业基准", "复购", "成分"],
    contextTriggers: [{ metric: "repurchase_rate" }],
    aiUsageHint: "美妆类退货率低但客诉成本高——过敏/假货投诉处理不当会造成品牌损失远超退货本身。",
  },
  {
    id: "benchmark_category_electronics",
    category: "industry_benchmark",
    title: "3C数码类目全指标基准（2026年）",
    content: "3C数码类目2026年行业基准：退货率2%-5%（质量要求高，但参数不符预期是主要退货原因）。支付转化率2%-4%（高客单决策周期长）。客单价¥200-2000（手机配件）/¥2000-8000（手机/平板）。复购率5%-10%（数码产品更换周期长）。毛利率10%-25%（品牌溢价空间有限），净利率约3%-10%。季节性：新品发布期（每年3-4月、9-10月）销量激增，旧款降价清仓。国补政策：2026年以旧换新/消费补贴持续，部分品类补贴可达15%。保修要求：3C类必须有明确保修承诺，无保修商品转化率下降40%+。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "京东3C行业报告2026 + 天猫数码数据", sourceUrl: "",
    confidence: 0.80,
    keywords: ["3C", "数码", "手机", "平板", "国补", "参数", "保修"],
    synonyms: ["电子产品", "数码产品", "3C数码", "消费电子"],
    tags: ["3C数码", "行业基准", "国补", "保修"],
    contextTriggers: [{ metric: "profit_margin" }],
    aiUsageHint: "3C数码净利率低（3%-10%），推广费用占比需严格控制在10%以内，否则极易亏损。",
  },
  {
    id: "benchmark_logistics_cost",
    category: "industry_benchmark",
    title: "各平台物流成本基准（2026年）",
    content: "电商物流成本行业参考（2026年）：1)快递费：江浙沪/珠三角省内约2-3元/单，跨省约4-8元/单，偏远地区（新疆/西藏/青海）约15-25元/单。2)包邮策略：客单价<30元商家需承担全部运费（约4-8元，占成本10%-25%）；客单价>100元通常包邮（运费已摊销）。3)仓储费：入仓费用约0.5-2元/件/月，大促期间仓储费上涨50%-100%。4)退货运费：商家承担退货运费约5-15元/单（视商品体积重量）。5)保价费：高价值商品保价费率约0.5%-1%。物流成本优化策略：集中仓储（靠近主要客户群）、与2-3家快递签约比价、大促前提前备货减少临时加急费。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "快递行业成本数据2026 + 电商仓储数据", sourceUrl: "",
    confidence: 0.80,
    keywords: ["快递费", "物流", "运费", "包邮", "仓储", "退货运费"],
    synonyms: ["物流成本", "快递成本", "运费成本", "配送"],
    tags: ["物流", "运费", "成本", "行业基准"],
    contextTriggers: [{ metric: "shipping_cost" }],
    aiUsageHint: "低客单价商品的运费占比往往被低估——¥20商品+¥6运费=运费占销售额30%。分析利润时必须包含运费。",
  },
  {
    id: "benchmark_promotion_depth",
    category: "industry_benchmark",
    title: "促销折扣力度与利润影响基准",
    content: "电商促销折扣深度参考（2026年）：1)日常促销：9折（9.5-9.9折）对利润影响约5%-10%，通常可承受。2)小促（38/99/618预热）：8-8.5折，利润压缩15%-25%。3)大促（618/双11）：6-7.5折，利润压缩30%-50%。4)清仓甩卖：5折以下，利润压缩>50%。⚠️ 促销叠加陷阱：平台满减+店铺优惠+优惠券+淘金币可能叠加到5折以上，实际让利远超预期。建议：促销前用'折后价÷原价'精确计算最终折扣率。促销后影响：大促后7-14天销量通常下滑30%-50%（透支效应），退货率上升20%-40%。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "电商促销策略研究2026", sourceUrl: "",
    confidence: 0.78,
    keywords: ["折扣", "促销", "打折", "满减", "优惠券", "大促"],
    synonyms: ["折扣力度", "促销深度", "让利", "降价"],
    tags: ["促销", "折扣", "利润影响", "行业基准"],
    contextTriggers: [{ metric: "discount_depth" }],
    aiUsageHint: "促销利润分析时，必须计算'折后毛利率'而非'原价毛利率'。大促后7-14天的销量下滑和退货增加也需纳入评估。",
  },
  {
    id: "benchmark_cac_by_platform",
    category: "industry_benchmark",
    title: "各平台获客成本（CAC）基准（2026年）",
    content: "各平台获客成本（CAC）参考（2026年）：1)淘宝/天猫：公域获客成本约150-400元/人（依赖直通车/引力魔方），私域复购获客成本约30-80元/人。2)京东：公域获客成本约200-500元/人（用户质量高但竞争激烈），会员体系复购获客成本约50-100元/人。3)拼多多：公域获客成本约50-150元/人（价格敏感用户，转化率高但客单价低）。4)抖音：公域获客成本约100-300元/人（内容种草+直播转化），粉丝获客成本约30-80元/人。⚠️ 2026年公域平均获客成本约280元/人，较2023年上涨47%。47.68%的商家将'流量成本太高'列为最大痛点。LTV/CAC比值健康值为>3，低于2说明获客效率低。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "电商行业获客成本报告2026", sourceUrl: "",
    confidence: 0.75,
    keywords: ["获客成本", "CAC", "用户获取", "流量成本", "拉新"],
    synonyms: ["获客", "拉新成本", "获客费用", "获客单价"],
    tags: ["获客", "CAC", "流量", "成本", "行业基准"],
    contextTriggers: [{ metric: "ad_cost" }],
    aiUsageHint: "获客成本持续上涨是行业趋势，建议商家通过私域运营/会员体系降低长期获客成本。",
  },
  {
    id: "benchmark_seasonal_sales",
    category: "industry_benchmark",
    title: "电商季节性销售波动规律（2026年）",
    content: "电商各月销售波动规律（2026年）：1)1月：年货节旺季，环比增长20%-40%，年后下滑。2)2月：春节低谷（物流停运+消费疲软），环比下降30%-50%。3)3月：38女王节+春季上新，环比回升30%-50%。4)4月：春游季+家装季，家居/户外类目旺季。5)5月：520表白季+五一长假，美妆/礼品类目小高峰。6月：618大促（全年第二大），环比增长100%-300%。7-8月：夏季淡季，环比下降20%-30%（空调/防晒品除外）。9月：99大促+开学季，环比回升。10月：双11预热期，蓄力增长。11月：双11（全年最大），环比增长200%-500%。12月：双12+年货预热，次高峰。分析销售数据时，必须用'同比'而非'环比'来消除季节性影响。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "电商行业月度销售规律2026", sourceUrl: "",
    confidence: 0.75,
    keywords: ["季节性", "月度波动", "淡旺季", "618", "双11", "年货"],
    synonyms: ["销售波动", "季节性规律", "月度趋势", "淡季旺季"],
    tags: ["季节性", "销售", "月度", "行业基准"],
    contextTriggers: [{ metric: "seasonality" }],
    aiUsageHint: "用YoY同比消除季节性。2月春节数据失真最严重——不要用2月数据做基准。",
  },
  {
    id: "benchmark_listing_optimization",
    category: "industry_benchmark",
    title: "商品详情页优化基准（2026年）",
    content: "商品详情页（Listing）优化标准（2026年）：1)主图：首图点击率>3%为合格，>5%为优秀。白底图/场景图/细节图至少3张，视频增加30%-50%转化。2)标题：30字以内，包含核心关键词+卖点+属性，前15字最重要。3)详情页：长度建议800-1500字，前3屏决定80%的停留决策。4)评价管理：好评率>95%，带图评价占比>20%，差评回复率100%。5)问大家：>10个问答且无负面回答可提升转化率10%+。6)视频：主图视频观看完成率>30%可提升转化20%+。7)A/B测试：同时测试2-3个版本，数据>1000次曝光后再决定。Listing优化的ROI通常是最高的——同样的流量，好的Listing转化率是差的3-5倍。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "电商运营优化标准2026", sourceUrl: "",
    confidence: 0.78,
    keywords: ["主图", "详情页", "标题", "评价", "转化率", "Listing"],
    synonyms: ["商品页", "详情页优化", "商品描述", "listing优化"],
    tags: ["Listing", "转化率", "优化", "行业基准"],
    contextTriggers: [{ metric: "conversion_rate" }],
    aiUsageHint: "转化率低时，优先检查主图点击率和详情页前3屏——这两个环节贡献了80%的流失。",
  },
  {
    id: "benchmark_platform_fee_percentage",
    category: "industry_benchmark",
    title: "电商全成本占比基准（2026年）",
    content: "电商商品总成本结构参考占比（2026年）：进货成本30%-60%（视品类），平台佣金2%-10%，运费3%-8%，广告推广10%-25%，退货损耗1%-5%，仓储物流2%-5%，人员及其他5%-15%。健康电商运营的总成本率应控制在75%-85%，净利率15%-25%。警戒线：总成本率>90%意味着几乎无利润空间。各成本项控制建议：1)进货成本→批量采购/多供应商比价 2)运费→集中仓储/快递谈判 3)广告→优化ROI，低于2.5暂停 4)退货→优化详情页/包装/尺码表。利润率连续3个月下滑时，按成本项逐一排查是最高效的诊断方法。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "电商财务分析标准2026", sourceUrl: "",
    confidence: 0.80,
    keywords: ["成本占比", "总成本", "成本结构", "利润率", "进货成本", "推广占比"],
    synonyms: ["成本率", "费用占比", "成本结构", "盈亏平衡"],
    tags: ["成本", "利润率", "结构", "行业基准"],
    contextTriggers: [{ metric: "profit_margin" }],
    aiUsageHint: "当用户利润率异常时，按成本结构逐项排查——广告>25%或退货>5%通常是最大问题项。",
  },
  {
    id: "benchmark_category_food",
    category: "industry_benchmark",
    title: "食品饮料类目全指标基准（2026年）",
    content: "食品饮料类目2026年行业基准：退货率1%-3%（极低，但临期/变质投诉影响大）。支付转化率4%-8%（低客单决策快，冲动消费多）。客单价¥30-100（零食）/¥50-200（礼盒）。复购率25%-40%（食品是高复购品类，尤其日常消费品）。毛利率20%-40%（标品竞争激烈），净利率约8%-15%。保质期管理：临期商品需提前3-6个月启动促销。食品安全：一次食安事故可导致品牌永久下架。溯源体系：2026年消费者越来越关注配料表和产地信息，透明化程度影响溢价能力。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫食品行业报告2026 + 拼多多食品数据", sourceUrl: "",
    confidence: 0.75,
    keywords: ["食品", "饮料", "零食", "临期", "保质期", "食安", "奶粉", "坚果", "糖果", "巧克力", "面包", "方便面", "蜜饯", "果干", "麦片", "咖啡", "茶叶", "蜂蜜", "火腿肠", "辣条"],
    synonyms: ["食品行业", "零食", "食品饮料", "快消食品"],
    tags: ["食品", "行业基准", "复购", "临期"],
    contextTriggers: [{ metric: "repurchase_rate" }],
    aiUsageHint: "食品类复购率高但毛利率低，利润增长靠走量而非提价。临期管理是关键——过期=全额损失。",
  },
  {
    id: "benchmark_category_home",
    category: "industry_benchmark",
    title: "家居日用类目全指标基准（2026年）",
    content: "家居日用类目2026年行业基准：退货率3%-8%（包装破损是主因，占退货的30%+）。支付转化率3%-5%（实用驱动型购买）。客单价¥50-300（日用百货）/¥200-1000（家居装饰）。复购率15%-25%（部分高频日用品复购率高）。毛利率30%-50%，净利率约12%-20%。季节性：Q1/Q2（春节/618装修季）为旺季，Q4（年货/年末大扫除）次之。包装要求：家居商品体积大重量沉，包装成本占总成本5%-10%，包装破损直接影响退货率和差评。安装服务：大家具类提供安装服务可提升转化率15%-20%。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫家居行业报告2026 + 京东居家数据", sourceUrl: "",
    confidence: 0.75,
    keywords: ["家居", "日用", "家具", "包装", "装修", "收纳", "毛巾", "床单", "枕头", "厨具", "餐具", "装饰", "垃圾桶", "保鲜盒", "衣架", "鞋柜", "书架", "桌布", "窗帘", "地毯"],
    synonyms: ["家居行业", "家居日用", "居家用品", "家装"],
    tags: ["家居", "行业基准", "包装", "季节性"],
    contextTriggers: [{ metric: "return_rate" }],
    aiUsageHint: "家居类退货主因是包装破损而非商品问题——优化包装可降低退货率3-5个百分点。",
  },
  {
    id: "benchmark_category_maternal",
    category: "industry_benchmark",
    title: "母婴用品类目全指标基准（2026年）",
    content: "母婴用品类目2026年行业基准：退货率3%-6%（品质要求极高，安全问题是退货主因）。支付转化率3%-6%（决策谨慎，但忠诚度高）。客单价¥100-500（奶粉/尿裤）/¥50-200（玩具）/¥100-300（童装）。复购率30%-50%（奶粉/尿裤是高复购核心品类）。毛利率25%-45%（品牌溢价空间大但竞争激烈），净利率约10%-18%。品质认证：3C认证/食品经营许可证/质检报告是硬性门槛。信任建设：母婴用户极度重视安全性，详情页展示质检报告和品牌故事可提升转化率20%+。季节性：新生儿礼盒在Q1（春节/年初生育高峰）销量最高。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫母婴行业报告2026 + 京东母婴数据", sourceUrl: "",
    confidence: 0.78,
    keywords: ["母婴", "奶粉", "尿裤", "玩具", "童装", "婴儿", "宝宝", "品质", "安全", "童鞋", "奶瓶", "奶嘴", "辅食", "米粉", "磨牙棒", "湿巾", "隔尿垫", "安全座椅", "婴儿车", "推车", "餐椅"],
    synonyms: ["母婴行业", "母婴用品", "婴幼儿", "宝妈"],
    tags: ["母婴", "行业基准", "复购", "品质"],
    contextTriggers: [{ metric: "repurchase_rate" }],
    aiUsageHint: "母婴类用户决策极度谨慎——信任是第一转化要素。质检报告和用户评价是核心信任信号。",
  },
  {
    id: "benchmark_category_sports",
    category: "industry_benchmark",
    title: "运动户外类目全指标基准（2026年）",
    content: "运动户外类目2026年行业基准：退货率5%-10%（尺码/功能不符是主因）。支付转化率3%-5%（专业驱动型购买）。客单价¥100-400（运动服饰）/¥200-1000（运动器材）/¥50-200（运动配件）。复购率20%-35%（运动鞋服中等复购，器材类偏低）。毛利率35%-55%（品牌溢价空间大），净利率约15%-25%。季节性：Q1/Q2（春季健身/户外露营旺季），Q3（夏季运动旺季），Q4（冬季运动/年货）。品牌效应：运动品牌用户忠诚度高，品牌认知度直接影响转化率30%+。功能诉求：用户购买决策重点关注功能参数（缓震/防水/透气）而非纯价格。内容营销：运动类目适合短视频/直播展示产品实际使用场景。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫运动户外行业报告2026 + 抖音运动数据", sourceUrl: "",
    confidence: 0.75,
    keywords: ["运动", "健身", "瑜伽", "跑步", "篮球", "足球", "运动鞋", "户外", "露营", "登山", "钓鱼", "骑行", "滑板", "轮滑", "哑铃", "瑜伽垫", "帐篷", "睡袋", "运动服", "运动裤", "运动背包", "运动水壶", "护膝", "护腕", "拉力器", "跳绳"],
    synonyms: ["运动行业", "运动户外", "健身用品", "户外用品"],
    tags: ["运动户外", "行业基准", "品牌", "季节性"],
    contextTriggers: [{ metric: "repurchase_rate" }],
    aiUsageHint: "运动类目用户重视品牌和功能——功能参数展示和真实使用场景视频是转化关键。",
  },
  {
    id: "benchmark_category_jewelry",
    category: "industry_benchmark",
    title: "珠宝饰品类目全指标基准（2026年）",
    content: "珠宝饰品类目2026年行业基准：退货率8%-15%（尺寸/佩戴效果与预期不符是主因）。支付转化率2%-4%（高客单决策周期长）。客单价¥50-300（时尚饰品）/¥500-5000（轻奢珠宝）/¥5000+（高端珠宝）。复购率10%-20%（珠宝购买频次低但客单价高）。毛利率45%-70%（高溢价空间），净利率约15%-30%。材质说明：925银/14K金/锆石等材质标注不清是退货主因。证书要求：贵金属和宝石需提供鉴定证书，否则转化率下降30%+。季节性：Q4（双11/年货送礼）为旺季，Q1（情人节/女神节）次之。直播带货：珠宝类目在抖音直播转化率高于传统电商——实物展示效果更直观。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "天猫珠宝行业报告2026 + 抖音珠宝数据", sourceUrl: "",
    confidence: 0.75,
    keywords: ["珠宝", "首饰", "戒指", "项链", "手链", "耳环", "手镯", "吊坠", "胸针", "发饰", "头饰", "脚链", "925银", "14K金", "钻石", "宝石", "珍珠", "水晶", "黄金", "铂金"],
    synonyms: ["珠宝行业", "珠宝饰品", "首饰", "饰品"],
    tags: ["珠宝", "行业基准", "材质", "证书"],
    contextTriggers: [{ metric: "return_rate" }],
    aiUsageHint: "珠宝退货率偏高——材质说明和尺寸标注是核心优化点。鉴定证书可提升转化率30%+。",
  },
  {
    id: "benchmark_category_appliance",
    category: "industry_benchmark",
    title: "家电类目全指标基准（2026年）",
    content: "家电类目2026年行业基准：退货率3%-7%（质量问题/安装服务是主因）。支付转化率2%-4%（高客单决策周期长）。客单价¥500-3000（小家电）/¥3000-10000（大家电）。复购率5%-15%（家电更换周期2-5年，复购率天然偏低）。毛利率15%-35%（大家电毛利薄但走量，小家电毛利高但竞争激烈），净利率约5%-15%。国补政策：2026年以旧换新/消费补贴持续，部分品类补贴可达15%，是重要促销杠杆。安装服务：大家电安装体验直接影响评价和退货率——提供免费安装可降低退货率2-4个百分点。能效标识：新国标能效等级影响用户购买决策，能效标签清晰可提升转化率10%+。保修承诺：3C类必须有明确保修承诺，无保修商品转化率下降40%+。",
    validFrom: "2026-01-01", validUntil: "2027-01-01", lastVerified: "2026-07-17",
    volatility: "annual",
    source: "京东家电行业报告2026 + 天猫家电数据", sourceUrl: "",
    confidence: 0.75,
    keywords: ["家电", "冰箱", "洗衣机", "空调", "电视", "吸尘器", "电饭煲", "电磁炉", "微波炉", "烤箱", "电水壶", "电风扇", "净化器", "加湿器", "电吹风", "剃须刀", "电动牙刷", "挂烫机", "扫地机器人", "洗碗机"],
    synonyms: ["家电行业", "家用电器", "白色家电", "黑色家电"],
    tags: ["家电", "行业基准", "国补", "安装"],
    contextTriggers: [{ metric: "profit_margin" }],
    aiUsageHint: "家电净利率低（5%-15%）——国补政策和安装服务质量是关键利润杠杆。",
  },

  // ═══════════════════════════════════════════════
  // 大类三：经营方法论 (methodology) — 11条
  // ═══════════════════════════════════════════════

  {
    id: "method_profit_decomposition",
    category: "methodology",
    title: "利润变动四因素拆解法",
    content: "利润变化可拆解为四个效应：1)价格效应—售价变动导致利润变化（降价促销→价格效应为负）2)销量效应—销量变动导致利润变化（降价后走量→销量效应为正）3)成本效应—成本结构变化导致利润变化（供应商涨价/佣金调整/达人分级变化）4)结构效应—产品组合变化导致利润变化（高利润品占比下降→结构效应为负）。总利润变化=价格效应+销量效应+成本效应+结构效应。分析方法：用基期数据分别替换每项因素，计算边际影响。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "管理会计学·利润分析标准方法论",
    confidence: 0.98,
    keywords: ["利润拆解", "利润变动", "价格效应", "销量效应", "成本效应", "结构效应"],
    synonyms: ["利润分解", "利润分析", "杜邦分析"],
    tags: ["利润", "分析方法", "经营"],
    aiUsageHint: "当用户问'利润为什么变了'时，用四因素法给出结构化的答案。这是我们的核心分析方法。",
  },
  {
    id: "method_multi_platform_pricing",
    category: "methodology",
    title: "多平台差异化定价策略",
    content: "同一商品在不同平台建议采用差异化定价：拼多多走量为主，定价=成本×1.2-1.5（低利润率、高周转）；淘宝主流价位，定价=成本×1.5-2.0（平衡利润与竞争力）；京东品质溢价，定价=成本×1.8-2.5（高客单、低退货率）；抖音内容溢价，定价=成本×2.0-3.0（需含达人佣金成本）。注意：1)各平台有最低价保护条款，跨平台价差不宜>30% 2)2026年六部门新规禁止基于用户画像的差异化定价 3)同一商品跨平台价差>30%会引发窜货和消费者信任危机。",
    validFrom: "2024-04-15", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "电商多平台运营实战手册",
    confidence: 0.75,
    keywords: ["定价", "多平台", "定价策略", "差异化", "价格"],
    synonyms: ["定价方法", "价格策略", "多平台定价", "差异化定价"],
    tags: ["定价", "多平台", "策略", "利润"],
    aiUsageHint: "给定价建议时，必须同时考虑平台的用户画像和竞争对手价格带。不可凭空给出数字。",
  },
  {
    id: "method_inventory_health",
    category: "methodology",
    title: "库存健康度评估方法",
    content: "库存健康度=库存周转天数。快消品健康值7-15天，3C数码30天，服装30-45天，家居60-90天。库存天数>90天→黄色预警（启动促销），>180天→红色预警（考虑清仓/捐赠/销毁）。资金占用成本=库存金额×月资金成本率（0.5%-1%）×积压月数。EOQ经济订货量模型：最优订货量=sqrt(2×年需求量×单次订货成本/单位持有成本)。安全库存=Z×σ×√L（Z=服务水平对应的安全因子，σ=需求标准差，L=提前期）。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "供应链管理经典理论",
    confidence: 0.95,
    keywords: ["库存", "缺货", "滞销", "周转", "库存天数", "EOQ", "安全库存"],
    synonyms: ["库存管理", "备货", "存货", "库存周转"],
    tags: ["库存", "供应链", "管理方法"],
    aiUsageHint: "库存分析需结合商品的销售数据。数据不足时（<30天），只能给出初步建议。",
  },
  {
    id: "method_product_lifecycle",
    category: "methodology",
    title: "商品生命周期判定与运营策略",
    content: "商品生命周期四阶段（基于最近90天数据判定）：🌱新品期：首次出现<30天，销量在上升。策略→观察转化率，考虑多平台测试，控制首批采购量。📈成长期：月环比增长率>15%，持续2个月以上。策略→确保供应，加大推广投放，考虑多平台铺货。⭐成熟期：增长率在±10%区间，销量稳定。策略→优化成本（谈更低进货价），防御竞品（关注竞品变价），寻找替代品储备。📉衰退期：连续2月环比下降>10%。策略→降价清仓（计算最优清仓价），或停止采购。⚠️淘汰预警：月销量<峰值的20%且持续下降。策略→立即停止采购，清仓回收资金。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "产品生命周期理论+电商实战经验",
    confidence: 0.92,
    keywords: ["生命周期", "新品", "成长", "成熟", "衰退", "淘汰"],
    synonyms: ["产品阶段", "商品阶段", "生命周期"],
    tags: ["生命周期", "商品管理", "运营策略"],
    aiUsageHint: "生命周期判定需要足够的销售历史数据（至少60天）。数据不足时标注'需要更多数据'。",
  },
  {
    id: "method_pareto_analysis",
    category: "methodology",
    title: "商品集中度与帕累托分析",
    content: "帕累托法则（二八定律）在电商中应用：通常TOP20%的商品贡献约80%的销售额/利润。集中度分析方法：1)计算每个商品销售额/利润占比 2)按降序排列计算累计占比 3)累计>80%的商品为核心品。集中度风险：TOP3商品占总额>60%→存在爆款依赖风险，一旦爆款出现问题（差评/断货/竞品），营业额将断崖式下跌。理想状态：TOP10商品贡献50%-60%的份额，剩余长尾商品贡献40%-50%。策略：培育腰部商品，降低对单一爆款的依赖。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "帕累托分析经典理论",
    confidence: 0.95,
    keywords: ["集中度", "帕累托", "二八", "TOP", "爆款", "长尾", "排名"],
    synonyms: ["集中度分析", "二八法则", "80/20", "TOP分析"],
    tags: ["集中度", "分析方法", "风险管理"],
    aiUsageHint: "发现集中度>60%时，应在分析中明确标注爆款依赖风险，并建议培育腰部商品。",
  },
  {
    id: "method_anomaly_detection",
    category: "methodology",
    title: "数据异常检测方法论",
    content: "电商数据异常四分类：1)统计异常—Z-score>3或IQR外，可能是自然波动也可能需要关注。2)趋势断裂—趋势方向突然改变（连续增长后突然下降/连续下降后突然增长），通常对应业务事件（促销/差评/断货/竞品变动）。3)关联异常—两个通常同向的指标出现背离（如销量↑利润↓→可能在降价促销）。4)结构异常—某维度占比突变（如某平台利润占比从30%骤降至15%）。分析流程：发现异常→定位时间段→检查对应事件→排除数据录入错误→给出业务解释→建议行动。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "统计学异常检测+电商数据分析经验",
    confidence: 0.90,
    keywords: ["异常", "异常检测", "异常值", "突变", "波动", "异常波动"],
    synonyms: ["数据异常", "离群值", "波动分析"],
    tags: ["异常检测", "分析方法", "数据质量"],
    aiUsageHint: "发现异常后，先确认不是数据质量问题（如平台导出格式错误），再给出业务解释。",
  },
  {
    id: "method_abc_classification",
    category: "methodology",
    title: "ABC库存分类管理法",
    content: "ABC分类法将商品按价值贡献分为三类：A类（TOP20%商品贡献约70%-80%销售额/利润）→重点管理，优先备货、重点监控库存、优先分配推广预算。B类（中间30%商品贡献约15%-25%）→常规管理，维持合理库存、适度推广。C类（底部50%商品贡献约5%-10%）→简化管理，低库存策略、最小化推广投入。分类标准：按销售额降序排列，累计占比前80%为A类，80%-95%为B类，95%-100%为C类。每季度重新分类一次——商品类别会随市场变化。⚠️ 注意：ABC分类只考虑销售额/利润贡献，不直接考虑周转率和库存天数，建议结合库存健康度一起分析。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "库存管理ABC分类法 + 电商实战",
    confidence: 0.95,
    keywords: ["ABC", "分类", "A类", "B类", "C类", "库存分类"],
    synonyms: ["ABC分析", "ABC库存", "重点品类", "二八法则"],
    tags: ["ABC", "库存", "分析方法", "分类"],
    aiUsageHint: "ABC分类是库存管理的起点——A类商品缺货影响最大，C类商品积压成本最低。",
  },
  {
    id: "method_rfm_segmentation",
    category: "methodology",
    title: "RFM 客户价值分层模型",
    content: "RFM模型通过三个维度将客户分层：1)R（Recency最近购买时间）—越近越有价值，近30天为活跃。2)F（Frequency购买频率）—频率越高忠诚度越高，月购≥3次为高频。3)M（Monetary消费金额）—金额越高价值越大，累计消费Top20%为高价值。组合出8类客户：重要价值客户(R近+F高+M高)→VIP维护；重要保持客户(R远+F高+M高)→召回活动；重要发展客户(R近+F低+M高)→提升频次；重要挽留客户(R远+F低+M高)→流失预警。执行要求：需要至少3个月的订单数据，数据不足时仅给出初步分层。工具：Excel透视表或RFM分析脚本均可实现。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "客户关系管理经典模型",
    confidence: 0.95,
    keywords: ["RFM", "客户分层", "客户价值", "最近购买", "购买频率", "消费金额"],
    synonyms: ["RFM分析", "客户分群", "用户分层", "客户分群"],
    tags: ["RFM", "客户价值", "CRM", "分析方法"],
    aiUsageHint: "RFM分析至少需要3个月数据。数据不足时，按最近购买时间和累计金额做简化分层。",
  },
  {
    id: "method_cohort_analysis",
    category: "methodology",
    title: "同期群分析（Cohort Analysis）",
    content: "同期群分析追踪相同时间段内获得的一群用户的长期行为。电商应用场景：1)新客留存分析——按注册月份分组，追踪每个群体的后续复购率。2)渠道质量分析——按获客渠道分组，比较各渠道的LTV和ROI。3)活动效果分析——按大促获客分组，评估大促新客的长期价值。执行步骤：1)定义同期群维度（注册月份/获客渠道/活动批次）。2)选择观察指标（复购率/ARPU/LTV）。3)绘制同期群热力图。4)识别高质量同期群的特征。关键发现：大促获客的30天留存率通常只有自然获客的30%-50%，但大促新客首单金额更高。建议：不要用简单平均复购率评估渠道质量，要用同期群对比。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "数据分析方法论 + 电商用户增长实践",
    confidence: 0.92,
    keywords: ["同期群", "cohort", "留存", "新客", "LTV", "用户分层"],
    synonyms: ["同期分析", "队列分析", "用户分组"],
    tags: ["同期群", "Cohort", "留存", "分析方法"],
    aiUsageHint: "同期群分析是评估渠道质量的最科学方法。大促新客的长期价值可能低于自然获客，不要只看首单ROI。",
  },
  {
    id: "method_sensitivity_analysis",
    category: "methodology",
    title: "利润敏感性分析",
    content: "利润敏感性分析评估各项变量变化对利润的影响程度。电商应用场景：1)价格弹性——降价10%对利润的影响（销量需增加多少才能弥补降价损失？）。2)成本弹性——进货价上涨10%对利润的影响。3)推广弹性——推广费用增加10%对利润的影响（需带来多少增量销售？）。4)退货率弹性——退货率上升2个点对利润的影响。执行方法：1)设定基准值（当前价格/成本/销量）。2)逐项变动±10%/±20%。3)计算利润变化百分比。4)排序敏感性（利润变动最大的因素为最敏感因素）。决策价值：敏感性分析帮助商家识别'利润杠杆'——改变哪个变量对利润影响最大，优先优化。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "管理会计·敏感性分析方法论",
    confidence: 0.92,
    keywords: ["敏感性", "利润敏感", "价格弹性", "成本敏感", "弹性分析"],
    synonyms: ["敏感性分析", "弹性分析", "利润杠杆"],
    tags: ["敏感性", "利润", "分析方法", "决策"],
    aiUsageHint: "当用户问'降价能不能带来更多利润'时，用敏感性分析回答——计算销量需增加多少才能弥补降价损失。",
  },
  {
    id: "method_sales_forecasting",
    category: "methodology",
    title: "销量预测方法",
    content: "电商销量预测常用方法：1)移动平均法——取最近N天平均销量，适合稳定商品。2)趋势外推法——基于历史趋势线性外推，适合成长期商品。3)季节性调整法——用去年同期数据±季节性系数，适合有明显季节性的商品。4)加权移动平均——近期数据权重更高，适合波动较大的商品。5)大促预估——大促销量=平日销量×大促倍数（618约3-8倍，双11约5-15倍，视品类）。执行要求：至少30天历史数据，数据越多越准。预测准确度评估：MAPE（平均绝对百分比误差）<15%为合格，<10%为优秀。用途：库存备货、人员排班、物流规划。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "时间序列预测 + 电商库存管理",
    confidence: 0.88,
    keywords: ["销量预测", "预测", "趋势", "季节性", "备货", "移动平均"],
    synonyms: ["销售预测", "销量预估", "需求预测", "库存预测"],
    tags: ["预测", "销量", "库存", "分析方法"],
    aiUsageHint: "销量预测至少需要30天数据。大促前建议用'平日×大促倍数'做快速估算。",
  },
  {
    id: "method_contribution_margin",
    category: "methodology",
    title: "贡献毛益分析与商品组合优化",
    content: "贡献毛益=销售额-变动成本（进货成本+平台佣金+运费+退货损耗）。贡献毛益率=贡献毛益/销售额。电商商品组合优化逻辑：1)计算每款商品的贡献毛益率。2)高贡献毛益率+高销量→明星商品，优先推广和备货。3)高贡献毛益率+低销量→潜力商品，加大推广测试。4)低贡献毛益率+高销量→现金牛商品，维持但控制成本。5)低贡献毛益率+低销量→问题商品/瘦狗商品，考虑下架。6)负贡献毛益→亏损商品，立即止损或调整定价。注意：贡献毛益分析不包含固定成本分摊（月租/人工），适用于短期商品决策。长期决策需考虑固定成本覆盖。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "管理会计·贡献毛益分析法",
    confidence: 0.92,
    keywords: ["贡献毛益", "边际贡献", "商品组合", "组合优化", "变动成本"],
    synonyms: ["边际贡献", "贡献分析", "商品结构"],
    tags: ["贡献毛益", "商品组合", "利润分析", "分析方法"],
    aiUsageHint: "贡献毛益分析是商品组合优化的核心工具——区分'赚钱的商品'和'看似赚钱实际亏钱的商品'。",
  },
  {
    id: "method_user_growth_funnel",
    category: "methodology",
    title: "电商转化漏斗与流失诊断",
    content: "电商核心转化漏斗（从流量到复购）：曝光→点击(CTR 2%-5%)→加购/收藏(10%-20%)→下单(20%-40%)→支付(70%-90%)→复购(10%-30%)。流失诊断方法：1)曝光到点击低→主图/价格/排名需优化。2)点击到加购低→详情页/评价/信任信号不足。3)加购到下单低→价格/优惠/紧迫感不足。4)下单到支付低→支付流程复杂/价格敏感。5)首购到复购低→产品体验/售后/会员体系不足。漏斗工具：神策/GA4/平台后台数据均可构建。关键行动：优先修复流失最大的环节（ROI最高）。通常曝光→点击和加购→下单是最大流失点。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商转化优化标准方法论",
    confidence: 0.90,
    keywords: ["转化漏斗", "流失", "CTR", "加购", "下单", "复购"],
    synonyms: ["转化路径", "漏斗分析", "流失分析", "转化率"],
    tags: ["转化漏斗", "流失诊断", "分析方法"],
    aiUsageHint: "转化率分析时，用漏斗定位最大流失环节。曝光→点击和加购→下单通常是最大流失点。",
  },
  {
    id: "method_lifecycle_profit",
    category: "methodology",
    title: "商品全生命周期利润模型",
    content: "商品从引入到退市的完整利润管理：1)导入期（0-30天）：销售额低，推广费用高，利润通常为负。容忍标准：导入期亏损不超过X元或X周，否则判定失败。2)成长期（30-90天）：销量快速增长，推广费用占比下降，开始盈利。重点：确保供应链跟得上销量增长。3)成熟期（90-365天）：销量稳定，利润达到峰值。重点：优化成本结构（谈更低进货价），控制退货率。4)衰退期（>365天或销量连续2月下降>10%）：利润下滑。策略：降价清仓/缩减SKU/寻找替代品。清仓定价：最低可接受售价=进货成本×0.7（保证不低于进货成本的70%）。商品生命周期分析需要：进货成本数据+全周期销售数据+退货数据。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "商品管理生命周期理论 + 电商实战",
    confidence: 0.90,
    keywords: ["生命周期", "导入期", "成长期", "成熟期", "衰退期", "清仓"],
    synonyms: ["商品周期", "产品周期", "生命周期利润"],
    tags: ["生命周期", "利润", "商品管理", "分析方法"],
    aiUsageHint: "商品生命周期分析需要至少90天数据。数据不足时只能给出'导入期/成长期'初步判断。",
  },

  // ═══════════════════════════════════════════════
  // 大类四：预警规则 (alert_rule) — 10条
  // ═══════════════════════════════════════════════

  {
    id: "alert_inventory_dead_stock",
    category: "alert_rule",
    title: "滞销库存预警规则",
    content: "滞销库存分级预警：库存天数>90天→黄色预警（启动促销，目标清掉30%库存）；>180天→红色预警（严重滞销，考虑清仓/捐赠/销毁）。资金占用成本计算：库存金额×月资金成本率（约0.5%-1%）×积压月数。例如：积压¥10,000×1%×6个月=¥600隐性损失。优先处理高价值滞销品（资金占用成本高），其次处理低价值滞销品（仓储成本占比高）。清仓定价公式：最低可接受售价=进货成本×（1-已积压月数×1%），保证不低于进货成本的80%。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "供应链管理+电商实战经验",
    confidence: 0.90,
    keywords: ["滞销", "积压", "库存预警", "清仓", "死库存"],
    synonyms: ["卖不动", "库存积压", "滞销品"],
    tags: ["预警", "库存", "滞销"],
    aiUsageHint: "计算滞销损失时，使用'库存金额×月资金成本率×积压月数'公式给出量化数字。",
  },
  {
    id: "alert_profit_loss_product",
    category: "alert_rule",
    title: "亏损商品预警规则",
    content: "商品亏损分级预警：1)单品净利率<0→🔴立即预警，建议停止采购/调整价格。2)单品毛利率>0但净利率<0→🟠平台扣费+运费+退货吃掉了毛利，建议分析哪个成本项是主因。3)单品净利率<行业均值的50%→🟡关注，建议对比竞品价格带和成本结构。4)亏损且销量大→🔴🔴最危险：卖得越多亏得越多，必须立即处理。5)亏损但销量小→🟡可以观察（可能是新品测试期）。注意：必须按各平台独立计算净利率，同一商品在淘宝赚钱在拼多多亏钱是常见现象。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "电商财务分析标准",
    confidence: 0.95,
    keywords: ["亏损", "亏钱", "负利润", "利润预警", "赔钱"],
    synonyms: ["不赚钱", "亏损品", "赔本品"],
    tags: ["预警", "亏损", "利润"],
    aiUsageHint: "⚠️ 这是最直接影响商家收入的预警。必须量化亏损金额和影响范围。'你每月在这些品上亏损¥X,XXX'比'这些品利润率低'有效10倍。",
  },
  {
    id: "alert_price_inversion",
    category: "alert_rule",
    title: "价格倒挂预警规则",
    content: "价格倒挂（售价<进货价）是严重的经营异常，必须立即预警。常见原因：1)促销后未及时回调价格（最常见）2)供应商涨价但零售价未调整 3)清仓甩卖策略（有意的，但需确认）4)数据录入错误（平台导出字段未清洗¥符号）。判断方法：售价/进货价<1→价格倒挂。售价/进货价<1.1→利润极薄，接近倒挂边缘。另外需检查跨平台价格一致性——同一商品在A平台售价¥59在B平台售价¥39，虽然没倒挂但差价30%可能引发窜货。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "电商价格管理标准",
    confidence: 0.95,
    keywords: ["价格倒挂", "售价比进价低", "定价错误", "售价低于进价"],
    synonyms: ["亏本卖", "低于成本", "价格异常"],
    tags: ["预警", "价格倒挂", "定价"],
    aiUsageHint: "⚠️ 发现价格倒挂，首先确认不是数据清洗问题（¥符号/元单位），再判断是否为有意清仓。",
  },
  {
    id: "alert_supplier_price_change",
    category: "alert_rule",
    title: "供应商涨价预警规则",
    content: "供应商涨价对利润的影响往往被低估。预警触发条件：1)供应商报价环比上涨>5%→黄色预警（需确认是否为临时调价）2)供应商报价环比上涨>15%→红色预警（必须寻找替代供应商）3)同一品类3个及以上供应商同时涨价→橙色预警（可能是原材料涨价传导，需调整全品类定价策略）。应对策略：1)至少维护2-3个备选供应商 2)进货价历史追踪，建立价格趋势图 3)批量采购折扣谈判（100-500件3%-5%，500-2000件5%-10%，2000+件10%-20%）。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "供应链管理+采购管理标准",
    confidence: 0.85,
    keywords: ["供应商", "涨价", "进货价", "采购成本", "报价"],
    synonyms: ["供价上涨", "进货涨价", "成本上涨"],
    tags: ["预警", "供应商", "成本"],
    aiUsageHint: "发现供应商涨价后，建议同时计算：1)如果接受涨价对利润的影响 2)如果换供应商的切换成本 3)如果提终端价的可行性。",
  },
  {
    id: "alert_return_rate_spike",
    category: "alert_rule",
    title: "退货率异常预警规则",
    content: "退货率异常是产品质量/描述问题的信号。预警级别：1)退货率>类目均值1.5倍→黄色预警（检查近30天退货原因分布）2)退货率>类目均值2倍→红色预警（检查产品批次质量/详情页描述准确性）3)周退货率环比增长>50%→紧急预警（可能是批次问题，建议暂停发货排查）。退货率每降低1%，利润直接提升1%（因为退货成本是纯损失）。差评响应时效控制在6小时内，差评转化率可降低40%。评分每提升0.1分，转化率提升3%-5%。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "电商运营+客户体验管理",
    confidence: 0.88,
    keywords: ["退货异常", "退货率飙升", "退款激增", "退单", "差评"],
    synonyms: ["退货猛增", "退款异常", "售后激增"],
    tags: ["预警", "退货率", "质量"],
    aiUsageHint: "退货率异常时，结合具体的退货原因（质量问题/描述不符/物流破损）给出针对性建议。",
  },
  {
    id: "alert_zero_sales",
    category: "alert_rule",
    title: "零动销/零销量商品预警规则",
    content: "零动销商品定义及处理：1)零动销—有库存但连续30天无销量。2)预警级别：30天无销→黄色预警（分析原因：价格/详情页/流量不足）；60天无销→橙色预警（启动清仓或下架）；90天无销→红色预警（立即清仓止损）。3)常见原因：价格高于竞品、主图吸引力不足、详情页描述不清、类目/标题关键词不匹配、库存不足导致搜索降权。4)处理方法：降价测试（降价10%-20%观察7天）→优化Listing（主图/标题/详情页）→报活动引流→清仓下架。5)零销量≠滞销：季节性商品可能在淡季零销量，需结合商品属性判断。资金占用成本同样适用——零销量但占用库存资金的商品，每月产生隐性损失。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商库存管理 + 商品运营实战",
    confidence: 0.90,
    keywords: ["零销量", "零动销", "没销量", "卖不动", "滞销"],
    synonyms: ["零销售", "无销量", "不动销", "滞销品"],
    tags: ["预警", "零销量", "动销", "库存"],
    aiUsageHint: "零动销是库存积压的前兆——30天无销就应启动处理，不要等到90天才行动。",
  },
  {
    id: "alert_review_crisis",
    category: "alert_rule",
    title: "差评/评价危机预警规则",
    content: "评价危机分级预警：1)差评率>3%→黄色预警（查看差评内容，确认是否为系统性质量问题）。2)差评率>5%→红色预警（检查是否有批量质量问题/物流大面积破损）。3)出现'假货'/'质量差'关键词→紧急处理（24小时内联系买家协商，避免扩散）。4)DSR评分下降>0.2分→关注（可能是近期差评或物流问题）。5)连续3天无新评价→可能流量在下降（平台算法降低排名）。处理时效要求：差评6小时内响应，DSR评分影响持续30天。回复策略：承认问题+说明改进措施+提供补偿方案。⚠️ 评价危机的影响：1个差评的负面影响力约等于10-20个好评。优质评价管理可提升转化率15%-25%。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商客户体验管理标准",
    confidence: 0.88,
    keywords: ["差评", "评价", "DSR", "评分下降", "好评率", "评价危机"],
    synonyms: ["差评管理", "评价管理", "评分预警", "口碑危机"],
    tags: ["预警", "评价", "DSR", "口碑"],
    aiUsageHint: "差评是转化率的隐形杀手——差评率>3%时应立即分析原因并制定改进方案。",
  },
  {
    id: "alert_campaign_roi",
    category: "alert_rule",
    title: "营销活动ROI预警规则",
    content: "营销活动效果评估标准：1)活动ROI<1→🔴立即停止活动，亏损中。2)活动ROI 1-1.5→🟠覆盖了推广成本但未覆盖隐性成本（人力/时间/库存占用）。3)活动ROI 1.5-2→🟡勉强达标，需分析是否值得继续。4)活动ROI>2→✅健康，可加大投入。5)活动ROI>5→⭐⭐优秀，分析成功因素并复制。⚠️ 特别注意：促销ROI必须用利润而非销售额计算。常见陷阱：销售额看起来增长了30%，但净利润反而下降了——因为满减+推广+退货损耗吃掉了利润。促销后遗症评估：大促后7-14天追踪退货率和销量恢复速度，退货率>40%说明促销吸引了非目标客户。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商营销效果评估标准",
    confidence: 0.88,
    keywords: ["活动ROI", "促销效果", "营销ROI", "活动评估", "大促ROI"],
    synonyms: ["促销ROI", "营销效果", "活动效果", "推广效果"],
    tags: ["预警", "活动", "ROI", "营销"],
    aiUsageHint: "促销ROI必须用利润计算而非销售额。销售额涨30%但净利润降20%是常见陷阱。",
  },
  {
    id: "alert_cashflow_risk",
    category: "alert_rule",
    title: "现金流风险预警规则",
    content: "电商现金流风险预警：1)应收账款/库存占用资金>月均销售额的50%→黄色预警（现金流紧张）。2)连续30天净现金流为负→橙色预警（需立即止损/融资/压货）。3)单一平台结算周期>30天+高库存→红色预警（断链风险）。4)应付账款到期日<回款日+30天→需提前安排资金。5)广告费/推广费占可用资金>30%→控制投放。电商现金流特点：先付款进货→推广引流→销售回款→平台结算（账期）。从进货到回款通常需要15-60天，此期间所有成本已支出但收入未到账。建议：1)保持至少1个月运营资金储备 2)监控'库存+应收/月均销售额'比值 3)账期管理：优先结算快的平台（京东POP T+1 vs 京东自营30-60天）。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商财务风险管理",
    confidence: 0.85,
    keywords: ["现金流", "资金", "账期", "应收账款", "资金风险", "回款"],
    synonyms: ["资金链", "现金风险", "资金管理", "现金流预警"],
    tags: ["预警", "现金流", "财务", "风险管理"],
    aiUsageHint: "电商现金流风险常被忽视——分析利润时必须同时分析现金流，否则可能'账面盈利但资金链断裂'。",
  },
  {
    id: "alert_platform_dependency",
    category: "alert_rule",
    title: "单平台依赖风险预警规则",
    content: "单平台依赖是电商经营的重大风险。预警标准：1)单一平台销售额占比>70%→黄色预警（过度依赖）。2)单一平台销售额占比>85%→红色预警（平台政策变动/封店/算法调整将导致营业额断崖）。3)单一爆款商品占平台销售额>50%→叠加风险。4)平台规则变化（费率上调/搜索算法调整/活动资格收紧）→立即评估影响。历史教训：天猫/淘宝搜索算法调整可导致流量下滑30%-50% overnight；拼多多'仅退款'政策导致部分商家退出；抖音达人分级变化影响佣金30%+。建议：1)至少布局2-3个平台 2)逐步将单平台占比降至50%以下 3)核心客户积累到私域（微信群/小程序） 4)关注平台政策变化，提前调整经营策略。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商多平台经营风险管理",
    confidence: 0.88,
    keywords: ["单平台", "依赖", "多平台", "分散风险", "平台政策"],
    synonyms: ["平台依赖", "单一平台", "渠道集中", "风险分散"],
    tags: ["预警", "平台", "多平台", "风险管理"],
    aiUsageHint: "单平台依赖是最大经营风险之一。分析跨平台数据时，应明确指出'您在XX平台占比XX%，建议分散渠道'。",
  },
  {
    id: "alert_pricing_error",
    category: "alert_rule",
    title: "定价错误/价格异常预警规则",
    content: "定价错误是电商最常见且损失最大的运营失误。常见类型及影响：1)折扣叠加错误：满减+优惠券+店铺折扣叠加后实际售价低于进货价→每单亏损。2)SKU价格错误：大促时部分SKU价格未同步更新→部分SKU亏本卖。3)区域价格错误：不同区域/渠道价格不一致→消费者投诉/窜货。4)规格换算错误：按件定价但用户按重量购买→实际售价低于预期。5)汇率/单位错误：进口商品按汇率换算错误导致定价偏差。6)未及时调价：成本上涨后未调整售价→利润持续下滑。预防措施：1)大促前用公式验证最终售价=原价-所有折扣 2)SKU价格矩阵检查表 3)设置价格下限制（不低于进货价×1.1）。发现定价错误后：立即下架→修正→评估已售订单是否需要补偿。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商运营风险管理",
    confidence: 0.92,
    keywords: ["定价错误", "价格错误", "价格异常", "亏本卖", "定价失误"],
    synonyms: ["定价失误", "价格bug", "价格异常", "定价问题"],
    tags: ["预警", "定价", "错误", "风险管理"],
    aiUsageHint: "大促后必须检查最终售价是否低于成本——定价错误是最大亏损来源之一。",
  },

  // ═══════════════════════════════════════════════
  // 大类五：供应链知识 (supply_chain) — 8条
  // ═══════════════════════════════════════════════

  {
    id: "supply_negotiate_batch_discount",
    category: "supply_chain",
    title: "批量采购折扣谈判参考",
    content: "一般供应商批量折扣梯度（2026年参考）：100件以下→无折扣，100-500件→3%-5%折扣，500-2000件→5%-10%折扣，2000+件→10%-20%折扣。建议策略：1)首次合作从小批量开始验证质量，稳定后谈阶梯价 2)同时询价至少3家供应商，拿到比价筹码 3)长期合作（>6个月）可谈月结/账期，缓解现金流压力 4)关注1688和京东货盘两个渠道——1688低价爆款vs京东货盘品质时效，根据销售渠道选择合适货源。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "供应链采购管理标准",
    confidence: 0.80,
    keywords: ["采购", "谈判", "供应商", "批量", "折扣", "1688"],
    synonyms: ["进货谈判", "议价", "采购折扣", "批量采购"],
    tags: ["采购", "谈判", "供应商", "成本"],
    aiUsageHint: "给采购建议时需结合商品的月销量数据——销量够大才值得谈批量折扣。",
  },
  {
    id: "supply_multiple_sources",
    category: "supply_chain",
    title: "多供应商策略与风险管理",
    content: "单一供应商依赖是供应链最大的风险之一。风险管理原则：1)核心品（占销售额>20%）至少2-3个备选供应商。2)供应商集中度：TOP1供应商占比<50%，TOP3供应商占比<80%。3)定期（每季度）重新询价至少2家新供应商。4)1688搜索同类产品最新报价，了解市场行情变化。5)供应商质量评估维度：价格竞争力、交货准时率、质量稳定性、配合度、账期灵活度。发现供应商涨价时，把历史价格数据作为谈判筹码。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "供应链风险管理标准",
    confidence: 0.88,
    keywords: ["多供应商", "备选", "供应链风险", "断货风险", "供应商管理"],
    synonyms: ["备选供应商", "供应商备份", "供应链安全"],
    tags: ["供应商", "风险管理", "采购"],
    aiUsageHint: "当发现用户只有一个供应商时，建议其至少再找2个备选。",
  },
  {
    id: "supply_data_cleaning",
    category: "supply_chain",
    title: "电商数据清洗标准流程",
    content: "电商数据清洗六步法：1)删除空行和完全重复行（按订单编号去重）。2)金额列去符号（¥/￥/元/美元），统一为数字格式。3)日期列统一格式为YYYY-MM-DD，识别并修正异常日期。4)异常值检测：数值超过均值±3倍标准差→标记但保留（可能为真实大单/批发单）。5)缺失值处理：关键字段（订单号/金额/日期）缺失→删除该行；非关键字段缺失→填充'未知'。6)平台字段标准化：不同平台的字段名映射到统一标准。特别注意：天猫/淘宝导出的金额字段常含¥符号和千分位逗号。京东自营和POP的数据口径不同，需分表处理。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-06",
    volatility: "evergreen",
    source: "数据清洗标准实践",
    confidence: 0.95,
    keywords: ["数据清洗", "缺失", "异常", "格式", "去重", "标准化"],
    synonyms: ["数据处理", "数据预处理", "清洗数据"],
    tags: ["数据清洗", "标准流程", "数据质量"],
    aiUsageHint: "当用户反馈数据看起来不对劲时，首先建议检查数据清洗是否正确。¥符号/千分位逗号是最常见问题。",
  },
  {
    id: "supply_logistics_cost_structure",
    category: "supply_chain",
    title: "物流成本结构与优化方法",
    content: "电商物流成本拆解（2026年）：1)快递费：省内2-3元/单，跨省4-8元/单，偏远地区15-25元/单。2)仓储费：入仓0.5-2元/件/月，大促期间上涨50%-100%。3)包材成本：纸箱+填充物约1-3元/件（视商品体积）。4)退货运费：商家承担5-15元/单。5)保价费：高价值商品0.5%-1%。总物流成本占销售额的8%-15%（视客单价和重量）。优化策略：1)快递谈判：月发货量>500单可谈3-5折，>5000单可谈2折。2)仓储布局：多区域分仓可降低平均配送成本20%-30%。3)包材优化：轻量化+标准化包装可降低包材成本20%-40%。4)退换货中心：集中处理退货可降低逆向物流成本30%。物流成本是影响低客单价商品利润的关键——¥20商品+¥6运费=运费占销售额30%。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "物流成本分析 + 电商供应链管理",
    confidence: 0.85,
    keywords: ["物流成本", "快递费", "包材", "仓储费", "退货运费", "逆向物流"],
    synonyms: ["运费成本", "物流费用", "配送成本", "快递成本"],
    tags: ["物流", "成本", "供应链", "优化"],
    aiUsageHint: "低客单价商品的运费占比常被忽视。分析利润时，如果运费占销售额>15%，应建议优化物流策略。",
  },
  {
    id: "supply_quality_control",
    category: "supply_chain",
    title: "供应商质量管控体系",
    content: "电商供应商质量管控六步法：1)准入评估：审核供应商资质（营业执照/生产许可证/质检报告），首单小批量试单。2)来料检验：按AQL标准抽检（一般水平：AQL=1.0，抽样比例按批量大小）。3)质量问题分级：致命缺陷（安全问题/功能失效）→立即停货；严重缺陷（影响外观/部分功能）→让步接收或退货；轻微缺陷（包装瑕疵/标签错误）→记录并跟踪。4)质量问题反馈：建立正式的质量反馈机制，要求供应商在3-7天内回复纠正措施。5)定期评估：每月评估来料合格率，连续3个月合格率<95%→启动替代供应商评估。6)备选供应商：核心品至少2-3个合格供应商。退货率异常时，首先排查进货批次质量——批质量问题可导致退货率骤升10%-20%。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "供应链质量管理标准",
    confidence: 0.88,
    keywords: ["质检", "质量管控", "来料检验", "AQL", "供应商质量", "批质量"],
    synonyms: ["品控", "质量管理", "质量检验", "供应商品控"],
    tags: ["质量管理", "供应商", "供应链", "品控"],
    aiUsageHint: "退货率突然上升时，首先检查是否为进货批次质量问题——批质量问题是退货率骤升的常见原因。",
  },
  {
    id: "supply_warehouse_strategy",
    category: "supply_chain",
    title: "仓储布局与库存分布策略",
    content: "电商仓储策略选择：1)中央仓模式：所有库存集中在单一仓库，管理简单但配送成本高（偏远地区配送慢且贵）。适合：SKU少、销量集中、起步阶段。2)区域分仓模式：在主要销售区域设多个仓库，配送快但管理复杂。适合：SKU多、销量分散、成熟阶段。3)入平台仓：使用平台物流（京东FBP/天猫菜鸟），消费者体验好但库存周转要求高（滞销品占用平台仓费用高）。4)一件代发：供应商直接发货，零库存风险但利润率低（供应商加价5%-15%）。分仓决策标准：当'跨区域配送成本'超过'分仓管理成本'时，应考虑分仓。粗略计算：月销量>5000单且跨省订单占比>40%时，分仓ROI为正。库存分布策略：核心SKU（A类）全国备货，区域热销SKU（B类）区域备货，长尾SKU（C类）中央仓。",
    validFrom: "2024-01-01", validUntil: "2099-12-31", lastVerified: "2026-07-17",
    volatility: "evergreen",
    source: "电商仓储与物流管理",
    confidence: 0.82,
    keywords: ["仓储", "分仓", "中央仓", "入仓", "一件代发", "库存分布"],
    synonyms: ["仓库布局", "仓储策略", "库存分布", "多仓"],
    tags: ["仓储", "库存", "供应链", "策略"],
    aiUsageHint: "仓储策略取决于销量规模和分布——月销5000单以上且跨省占比>40%时，区域分仓开始有ROI。",
  },
];

// ============================================================
// 检索函数
// ============================================================

/** 按关键词匹配检索（保留向后兼容）+ 增加同义词扩展 */
export function searchKnowledge(query: string, maxResults: number = 5): KnowledgeEntry[] {
  const q = query.toLowerCase();
  const scored = KNOWLEDGE.map(function(item) {
    // 主关键词命中
    const kwHits = item.keywords.filter(function(k) { return q.includes(k.toLowerCase()); });
    // 同义词命中（权重0.5）
    const synHits = (item.synonyms || []).filter(function(s) { return q.includes(s.toLowerCase()); });
    const score = kwHits.length + synHits.length * 0.5;
    return { entry: item, score: score };
  }).filter(function(item) { return item.score > 0; });
  scored.sort(function(a, b) { return b.score - a.score; });
  return scored.slice(0, maxResults).map(function(item) { return item.entry; });
}

/** 按标签和平台筛选 */
export function searchByTags(tags: string[], maxResults: number = 10): KnowledgeEntry[] {
  return KNOWLEDGE.filter(function(entry) {
    return tags.some(function(t) { return entry.tags.includes(t); });
  }).slice(0, maxResults);
}

/** 按平台触发上下文检索 */
export function searchByPlatform(platform: string): KnowledgeEntry[] {
  return KNOWLEDGE.filter(function(entry) {
    return entry.contextTriggers?.some(function(ct) { return ct.platform === platform; });
  });
}

/** 获取知识库统计信息 */
export function getKnowledgeStats() {
  const total = KNOWLEDGE.length;
  const byCategory: Record<string, number> = {};
  const byVolatility: Record<string, number> = {};
  const byTier: Record<string, number> = {};
  let expiredCount = 0;
  const now = new Date().toISOString();

  for (const entry of KNOWLEDGE) {
    byCategory[entry.category] = (byCategory[entry.category] || 0) + 1;
    byVolatility[entry.volatility] = (byVolatility[entry.volatility] || 0) + 1;

    if (entry.confidence >= 0.90) byTier["tier1"] = (byTier["tier1"] || 0) + 1;
    else if (entry.confidence >= 0.70) byTier["tier2"] = (byTier["tier2"] || 0) + 1;
    else byTier["tier3"] = (byTier["tier3"] || 0) + 1;

    if (entry.validUntil < now) expiredCount++;
  }

  return {
    total,
    expiredCount,
    freshnessRate: Math.round((total - expiredCount) / total * 100),
    byCategory,
    byVolatility,
    byTier,
    lastUpdated: "2026-07-06",
  };
}
